### ISSUE TITLE
Blue Portal Description

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#101]
I may be wrong, but I think the blue portal restores mana. Its description does not convey this.

**Comment by jdoleary** [comment]
It heals `        takeDamage(player.unit, -RED_PORTAL_DAMAGE, undefined, underworld, false);`
it's the opposite of a red portal

**Comment by SoulMuncher** [comment]
Interesting. If that's the case, there could've been other things going on at the time. Multiplayer sync, spells refunds, etc. Who knows.

I will definitely keep a closer eye on this and try to repro some time.
