### ISSUE TITLE
Weak Resurrect Description

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#102]
The description says the unit will be revived with 10% health. It does not mention that the unit will only have 10% mana as well (a potentially game changing piece of information that should be conveyed to the player)

**Comment by jdoleary** [comment]
Text changes are a HUGE pain in the ass because I have to double check every language localization.  It just takes a lot of time.  So you're 100% right here, but I consider text changes super low priority unless they're very important.

**Comment by SoulMuncher** [comment]
I would say this is a fairly important text change, as it could easily cost you a run (say you revive a teammate and expect them to have mana on spawn, but they don't, so then you're both screwed).

Maybe weak resurrect could res units with their usual starting mana: Mana units are often useless with the spell. Players would res with full mana

**Comment by jdoleary** [comment]
Fixed in 4dcd466f
No text change needed.
