### ISSUE TITLE
Recording Issue (GeForce and Twitch)

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#105]
I can't record the game with Nvidia's GeForce experience, despite being able to otherwise capture my entire screen, and all other applications I have used.

Would definitely help in spotting, recording, and reproducing bugs in the future. No idea where to start though. Probably a good thing to look into when the bug list is a little shorter.

**Comment by jdoleary** [comment]
Possible solutions:
- Enable hardware acceleration in electron https://stackoverflow.com/questions/62678626/enabling-hardware-acceleration-in-electron-app (this will have to be done in the Electron repo that builds spellmasons as an electron app)
- Add Spellmasons as a "game" in the GeForce experience settings (this can be done on the user's computer)

**Comment by SoulMuncher** [comment]
I've noticed that Twitch also struggles to capture the game window, and you have to enable the compatibility mode for it to work, which is sometimes less reliable and costs more computer resources.

This may be slightly higher prio than I thought initially

**Comment by jdoleary** [comment]
Some background: Spellmasons is made into an exe with Electron.js, so it's likely that Electron is the problem.  You're welcome to research this, and I will give you access to the electron repository that builds Spellmasons.

**Comment by jdoleary** [comment]
Oh it looks like you already have access to it.  It's called `Golems-Electron-Build`

**Comment by jdoleary** [comment]
@SoulMuncher I was just able to record with GeForce.  I didn't use shadowplay but I used their regular screen recording with Alt+z and then clicked "Record".
How did you attempt to record?

**Comment by SoulMuncher** [comment]
@jdoleary

Just tested in the latest steam release. Neither instant replay nor the standard recording method you used work for me.

How long was your recording? Its normal for it to work for a few seconds or up to a minute, the recording issues seem to be tied to certain game events. You may need to choose a couple of spells or complete a couple of levels to see the recording freeze up. Also make sure you are in fullscreen, as this is the only time I have had any issues with GeForce.

**Comment by jdoleary** [comment]
I was in fullscreen but I only recorded for about 15 seconds.  I did cast a spell without issue
