### ISSUE TITLE
Class: No targeting spells

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#107]
Idea for a class that can't use targeting spells and gets some other significant buff/advantage in its place.

Theme and name ideas?
- Barbaric and brute-y?
- Stealthy Assassin-y?
- Self-taught prodigy mage that skipped the chapter on targeting spells?

What would the advantage be? Ideas:
- All ramping mana costs reset each turn
- A cheap teleport spell
- Significant multipliers to all stats

**Comment by jdoleary** [comment]
Whoa that'd be wild.  Interesting idea!  I'd love to hear more.
