### ISSUE TITLE
Player Mana Regen

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#111]
Just wanted to talk about it. It seems like a feature that was removed at one point and thinking about stats in #86 made me wonder if mana regen would be a more interesting stat/mechanic than stamina, and if it would be worth reintroducing.

Some contextual changes I think would go with it:
- More max mana for players
- Start each level at [Mana Regen] mana, instead of max
- A look at 'Mana' spells to ensure balance is kept
- Stamina could be removed from stat upgrade options. Might still be modified by mage type, spells, status effects, etc.

**Comment by jdoleary** [comment]
So like only regen 50% mana or somethiing instead of 100% per turn?  That could be interesting.  Maybe in a mage class instead of default tho

**Comment by SoulMuncher** [comment]
@jdoleary 
Yeah kinda. The idea was that they would be two unattached stats you could upgrade on level up.

Let's say you start the game with 100 max mana and 50 regen per turn.

From there, you could allocate your stat points in such a way that you now have 100 max and 100 regen, giving you a respectable amount of mana every turn to adapt to the immediate situation. You could also go straight for 200 max and make do with only 50 regen. You may have trouble surviving and conserving your mana, but if you're clever enough to pull it off, the increased maximum would give you far more potential for those giant map-nuking-resurrect combos. In most cases, you would likely want to maintain a balance of both, but you could gear your character more towards the playstyle you enjoy.

- I like the strategical implications of deciding between saving your mana and spending it now. Having the ability to "charge up" and unleash everything at once.
- I like the idea of not starting each level at full mana. It becomes much more difficult to map-nuke or take out all the summoners turn 1, without getting rid of the player's ability to do that. You can still be awesome, you just have to be a bit more creative and strategic in getting to that point (turn 3 or 4 in a round).
- This also means more enemy interaction and difficulty.
- It may also be a functional way to "nerf" the mana stat, by having you distribute it across two different stats, without making the player less capable of casting cool spells in the early and mid-game.

**Comment by jdoleary** [comment]
I think I like this idea.  I'll have to think on it more, but for now, I find it compelling - especially since players can choose what stats to allocate points to (they didn't use to be able to).
