### ISSUE TITLE
Impending Doom + Contaminate

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#118]
I haven't tested but I just realized that when I changed impending doom from a "spell" to a modifier, it lost its “curse” classification, meaning it won't be removed by purify anymore.

What do we want to do about this?
- Make it a curse for the purposes of purify, contaminate, etc.
- Leave it the way it is and consider it a nerf to Toxic Res?
- Something else?

**Comment by jdoleary** [comment]
It should still be a curse.  The current code is `      getOrInitModifier(unit, impendingDoomId, { isCurse: true, quantity, persistBetweenLevels: false }, () => {`
I want it to remain a curse so we have the toxic resurrrect + purify synergy.  It's a clever one and I want to reward players for thinking of it

**Comment by SoulMuncher** [comment]
Oops, you're correct that toxic res + purify works as intended!

I did check contaminate though, and it does not spread impending doom, because it specifically checks for "cards". Going to fix this and update the issue. 👍
