### ISSUE TITLE
Decoy health scales with difficulty

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#12]
Summon decoy calls unit.create(), which automatically calls unit.adjustUnitDifficulty(), raising its health. This may also affect player summons, but I haven't been able to test it due to no setDifficulty function.

Depending on your design choices, multiple solutions could be used. One option would be to have a createUnscaled() function that prevents a created unit's stats from being auto adjusted by difficulty. This could be used for all summons?
It could be a parameter/overload as well, but it's a pretty frequently used function so it may take some time to update everywhere that uses it.

**Comment by jdoleary** [comment]
I'll have to think about this.  I think summons should match the stats of the enemies in game. so if you summon a golem it shouldn't be unscaled.  I'll assign this to myself for now for future consideration.

**Comment by SoulMuncher** [comment]
Sure. The new stat system may fix this anyway, so I wouldn't worry about it too much as of right now. Let's see what needs to be done after the stat system.

**Comment by SoulMuncher** [comment]
Deemed an intentional game mechanic for all player summons
