### ISSUE TITLE
Investigate err: "raceTimeout: moveTowards; Spellmason"

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#125]

**Comment by jdoleary** [comment]
1302 instances
12/8/2023, 9:43:37 AM
12/11/2023, 7:20:33 AM
1.25.0
BROWSER
ERROR

**Comment by SoulMuncher** [comment]
Fixed with https://github.com/jdoleary/Spellmasons/commit/e1bc833469cdaef1f71a599479768770bdb4ab89 ?
