### ISSUE TITLE
Investigate err: 'Unexpected: Created pickup at NaN Portal'

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#126]
184 instances
12/8/2023, 11:58:05 AM
12/11/2023, 6:37:29 AM
1.25.0
BROWSER
ERROR

**Comment by SoulMuncher** [comment]
Fixed with https://github.com/jdoleary/Spellmasons/commit/5caa5f7a034c09e10dec5691d31b88d580b65c4d?
