### ISSUE TITLE
Split account for quantity

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#133]
If I apply split 2 to a unit, it's stats should be halved twice, instead of once.

(Relevant for contaminate)

**Comment by jdoleary** [comment]
Hmm this is curious because split is both a modifier and a spell.  Should contaminate cause it to actually split again (like the spell effect)?

**Comment by jdoleary** [comment]
Just tested it, you can contaminate split and it passes along the size and stat changes but doesn't re-split.  I actually think this is awesome and exactly what it should do.  It's an amazing synergy cause you can drastically weaken a unit without creating a second one of them.  Brilliant!
