### ISSUE TITLE
Keep modifiers on death

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#137]
There is no way to force a unit to keep a modifier through death. Maybe it would be worth adding a boolean in the Modifier interface or changing this default behavior.

I'm looking at Split (#135 ), Contaminate, Vampires (units with innate/persistent status effects), future possibilities like a cheat death blessing that triggers on the dead unit's next turn start, corpse explosions, etc.

**Comment by jdoleary** [comment]
Great idea, `keepOnDeath` would be perfect as an optional modifier boolean
