### ISSUE TITLE
Idea: Summonable trap that stores a spell in it

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#140]
> Jordan - Spellmasons Creator — Today at 4:02 PM
> This used to be in the game a long time ago and @meme_man just suggested the same in ⁠suggestions-and-feedback .  I had to remove it due to unforseen complexities but it sounds like it's a popular request so maybe I'll revisit it.
> 

Idea: meme_man and Vinnick Talberot

**Comment by SoulMuncher** [comment]
Related #17 

Possibly useful from @ KyroBright
https://discord.com/channels/1032294536640200766/1060649713679994900/1193750507014066236
