### ISSUE TITLE
Vinnick's Monster Ideas

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#142]
> VinnickTalberot — Today at 4:26 PM
> Beacon enemies, that when they become part of a target effect, block any future target effects for the whole spell afterward. Like if you had connect + similar + connect, and the beacon enemy is effected during the "similar" stage, all targets added with connect would be unaffected. A late game addition that could help lower the "nuke" strategy.
> Maybe a ghoul enemy that will consume corpses to become stronger. 
> 
> A necromancer that will raise skeletons from corpses (leaving the corpses in tact)
> 
> Skeletons that have a 50% chance to rise again if defeated. 
> 
> Dragon boss, with a cone attack and an automatic "pull/vortex" effect on all targets on the map each turn. 
> 
> Blink dogs that teleport across the map at random, and if they get hit they cause their attacker to be displaced.
> A rare Djinn boss that will start off hostile, with a small percent chance to steal a spell from you, but if you cast a blessing on them they grant you a random spell.
> VinnickTalberot — Today at 4:33 PM
> Golems that are immune to a certain number of spells. So the first say.. three spells that hit them are nullified, but then they can be effected.

**Comment by SoulMuncher** [comment]
The beacon is interesting. I wonder if that can work more as an aoe forcefield, preventing nearby things from being targeted. That might work well with the aura system you were talking about.

It's also good to think about adding some things that aren't necessarily there just to fight you, like the Djinn. Rare neutral faction monster that pulls all nearby units into liquid. Roaming rat swarm that feasts on corpses. Little goblin that runs around and tries to steal all the pickups/hides behind urns. Neutral units that befriend you if you bless them. There's definitely potential within that realm of thinking.

**Comment by jdoleary** [comment]
Yeah I agree, more environmental hazards that are dangerous for both the player and enemies are cool because then the player can intelligently use them. That was the idea with traps and liquid (and now urns) but there's probably a lot more than could be done there.  
Vinnick also mentioned a rune that lets you start with an ally (similar to the neutral units that you can befrend) and I really like that idea.  Maybe there could be miniquests, where if you keep your friend alive for 5 levels they give you a gift or something.  A lot could be done in this area for sure
