### ISSUE TITLE
Moonlighter Multiplayer bug report

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#148]
A clear description of the rejoin as a fresh player and desync issues that have been popping up.
@SoulMuncher I've been trying to repro this but haven't been able to.  It's supposed to have players auto rejoin as their names from the previous session, not sure why it's not.  If you have any ideas, please share.  I'm a little stumped on this one.
 
> https://discord.com/channels/1032294536640200766/1069963955092606976/1184750893984403506
> 
> 5 players. A summoner tried to teleport - we were getting a bit laggy before that. Then everyone got booted (their names turned into UID codes?) - they re-joined and got to rechoose their spells, but their stats are back to basics
> the summoner who teleported is the bottom left one - he is bloated, but his sprite does not appear to be
> we then completed the level and it gave the guys the ability to get their stats again, but not their captured souls
> Moonlighter — Today at 2:12 AM
> These guys are dead. We watched them die, but then they're back. They'll probably die when everyone ends their turn (it was a bloat slash combo)
> Image
> and they didn't die when that happened again... so then they died again but killed my teammate
> Moonlighter — Today at 2:28 AM
> Let me know if you don't want this stuff or if you need more data 
> Image
> game stalled here - two people tried to cast spells at the same time (not host) - we couldn't see each other move, as an example. When the host tried to save, it started up again, but then we couldn't pick spells

**Comment by jdoleary** [comment]
> My son agreed - they got booted twice, once came back to lobby, once got jumped straight in, but he doesn’t remember seeing a “join as this player” button

**Comment by SoulMuncher** [comment]
@jdoleary
I'm stumped too. I'd like to fix it soon, but without any leads/repro it might be better to keep fixing the desync/await issues that we already know about (#63 #147) and come back to this it's not resolved in the 1.26 release? It might be easier to spot after the other issues are cleared up.

**Comment by SoulMuncher** [comment]
Could be worth putting out a test build if we get the other 2 issues resolved early enough.

**Comment by jdoleary** [comment]
I will have #147 finished tomorrow.  I think it might solve this issue too.  I think I'll let the clients generate their own clientIds instead of the server and that will ensure that their clientId never changes which means they won't auto generate a new player when they rejoin a room.

**Comment by jdoleary** [comment]
I think this is fixed since the last update
