### ISSUE TITLE
Decoy bug

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#151]
> Moonlighter — Today at 12:29 PM
> I guess we’ve had decoy troubles - sometimes they target us still, either not changing targets when cast, or costing us instead on a new turn despite decoy being closer.
> Literally just happened
> Jordan - Spellmasons Creator — Today at 12:34 PM
> Hmm, so if a decoy is going to be killed by another NPC they'll ignore it since it's already handled by another enemy.
> Could that be what's going on?

> Moonlighter — Today at 1:42 PM
> No. Decoy lives to the next turn most of the time.

**Comment by SoulMuncher** [comment]
Wonder if this has to do with ally summons changing the enemy state between when you see the attention markers and when the enemies move. Iirc this was a multiplayer game with 5+ people.

Decoy also has some issues where sometimes an enemy has an attention marker, but decides to attack the decoy instead next turn.

**Comment by jdoleary** [comment]
Could be, I haven't seen this so we'll need to make it reproducable

**Comment by jdoleary** [comment]
Related to #291?

**Comment by jdoleary** [comment]
#291 is closed now, i'll close this and we can reopen if it's reported again.
