### ISSUE TITLE
Bloat radius label

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#153]
If you give a golem bloat and select it, it shows it's attack radius and it's explosion radius but the explosion radius isn't labelled.
Not sure how we should resolve this.
Also, the bloat radius should be grey, not red, if the unit is out of bounds of a spell when you go to cast a spell that would kill it.

**Comment by SoulMuncher** [comment]
I think the grey thing was fixed in #146 
Will double check tomorrow!

**Comment by SoulMuncher** [comment]
Confirmed info as of Jan 30th, steam version 1.27.2

There is still an issue where only one text label can exist at a time, so the "explosion radius" label doesn't exist when selecting a unit that has attack range. Do we allow multiple labels? Check previous discussion in #146 

The grey radius issue is fixed. The radius appears grey when the unit is out of bounds of a spell when you go to cast a spell that would kill it.
