### ISSUE TITLE
Stat idea: Armor

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#155]
> VinnickTalberot — Today at 9:20 PM
> Possibly like a damage reduction against each individual attack. Like another levelup stat. It could allow for more "tanky" builds. Maybe 2 points per level. You wouldn't be able to fully block all attacks until around the deathmason, and then after that you'd be dealing with enemies having increased power. I'd also suggest that poison should bypass armor.
> It could also allow for spells that give a bonus to damage reduction of some sort. Good for the cleric builds, or something to apply to summons
> And it could maybe be a stat added to some enemies, or used for new types. Like an iron golem or something.
> I'm going to add some of those ideas to the mob idea thread
> VinnickTalberot — Today at 9:31 PM
> But yeah, having a damage reduction stat would greatly increase survivability, and would scale against the increasing numbers of enemies. Maybe you could even create a Knight class that focuses on that stat.
> VinnickTalberot — Today at 9:39 PM
> Is Spellmasons trying for indie of the year or any of the steam awards?
> Skillo — Today at 10:20 PM
> Some games make enemies tankier by giving them damage negation stacks 
> 
> Like the first or second hit shred their armor and then you start dealing direct damage 
> 
> Dots naturally ignore this
> Other things like drown, suffocate, etc
> VinnickTalberot — Today at 10:23 PM
> Well I don't think shredding the armor should be the point. There's already a shield spell.
> VinnickTalberot — Today at 10:37 PM
> I was thinking something more like a levelup bonus where you could maybe get like... 1 or 2 points of damage reduction per point used. So 3 points would give you 6 armor, which would block six from every enemy attack. Allowing your health to mean more in the long run, but also keeping the boss enemies as a danger because they still have a higher percentage of their damage getting through.

**Comment by Couls** [comment]
If this were to be included I highly recommend its on a specialized class, rather than a feature every character has it may be a bit too powerful to get really high defense, some kind of Vanguardmason or Knightmason would be neat, potentially even a spellswordmason using this mechanic as well
