### ISSUE TITLE
Stamina/Momentum Class

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#156]
- Momentum: Deal max stamina / 10 extra damage to the first enemy you hit each turn
- With each kill, refill stamina and reset momentum
- +50% stamina
- Can't use arrows (and/or targeting spells)?

For balance/playstyle: Momentum needs to be phrased/implemented/balanced in such a way that you have to use the reset to get good value out of it. I.E. You can't just target everything at once and deal extra damage to all of them. The idea is that the player is rewarded for having and using stamina, moving around the map with small spells, and focusing on single targets.

Some considerations: How does this work if the player uses something like target circle+slash? Are targets added in order by distance to the middle of the circle? That might work out fine, if you just deal extra damage to the first target added to the spell. Momentum might need a cool visual effect when it triggers too!

Similar Ideas:
- Swordmason
  - Slash costs stamina but is 5x more expensive
  - Restore stamina on kill
  - +100% stamina
- Static
  - Build up static charge while moving/dashing/repeling around, unleash it the next time you deal damage (maybe to all targets, maybe it chains like lightning, maybe that's a new spell entirely)
  - +50% stamina
- Alchemist
  - Grants Last Will
  - Potions do something special
  - +100% stamina

**Comment by jdoleary** [comment]
> With each kill, refill stamina and reset momentum

THIS is an awesome idea!
I love all these ideas.  Someone in Discord mentioned keeping track of how far you move (through stamina and forceMove) and having that number affect spells, like if you dash really far before casting it does more damage or something.  These ideas are definitely worth future consideration.

Also there was the idea of "runes" (similar to slay the spire).  It might be that we just do away with the idea of classes entirely and add runes instead which could enable things like "With each kill, refill stamina and reset momentum" or "arrow spells don't get more expensive".  The idea here is that through combinations of runes you'd get vastly different play sessions whereas if we just keep getting classes they don't interact with anything beyond themselves.

**Comment by SoulMuncher** [comment]
Runes could be pretty interesting 😄

**Comment by jdoleary** [comment]
Yeah I think classes were a good start but I'm leaning towards replacing them with runes.   Let's keep going with ideas like you had above, these are great, but I think I want them to be combinable instead of isolated.
