### ISSUE TITLE
Target Column should grow in *length* when stacked, not in width

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#16]
Seems like no one likes or uses target column. As you suggested in your feedback, its the "go-to range extender" so stacking it should make it longer.

FYI, if a change requires a text change to a spell label, that has to get translated so add a TODO for me to update the translation

**Comment by SoulMuncher** [comment]
In theory, column _should_ be the go-to range extender, but it's objectively worse than cone in most scenarios.
![ConeColumn](https://github.com/jdoleary/Spellmasons/assets/68413161/7c8106ee-cbd9-47b8-8e6a-d0c6a9b074f5)

Currently column 200 range and cone has 240. I think swapping these range values in addition to the change you listed above might help make the two less comparable, and more geared towards a specific purpose. Will hit you with a pull request soon
