### ISSUE TITLE
HP bars not updating between stacked slash on golem

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#166]

**Comment by SoulMuncher** [comment]
This happens when you queue up a spell while another one is still running, common in multiplayer.

The prediction is drawing "healing" values behind current health values because the prediction does not take into consideration the spell that is still going behind it.

Might be complicated to fix

**Comment by jdoleary** [comment]
> Not sure how to check that for single/multi player

You could have a flag that gets set once a SPELL message starts processing and is cleared after it's done.
