### ISSUE TITLE
Mage Scholar

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#17]
This will be complicated and shouldn't be pursued yet, but I like the idea so I'm storing it here for later.

SoulMuncher:
Targetting Spell Idea: Summon a mage scholar that attempts to cast the constructed spell at/on the nearest enemy every turn. The entity would be limited by mana regen. Multi-casting the targetting spell would give the mage more hp/mana regen/stamina/starting mana? (Sidenote: Would there be two versions, one that targets allies and one that targets enemies? Would it be determined by the first spell effect in the list?)

Jordan:
"Spells that last several turns " this is the vision for "auras" which have been on my list for a while but I haven't gotten to yet
Mage scholar idea is cool.  I messed with a similar idea early on (trap was a spell that stored the rest of your spell in a pickup that would trigger later).  I think it's worth revisiting.  Balance might be hard, but maybe not if it costs mana for the scholar to cast then the balance is built in.

**Comment by SoulMuncher** [comment]
Possibly useful from @ KyroBright
https://discord.com/channels/1032294536640200766/1060649713679994900/1193750507014066236
