### ISSUE TITLE
Sometimes old upgraded spells return to your hotbar

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#19]
The old versions of upgrades spells are not supposed to be available after the upgrade.
https://discord.com/channels/1032294536640200766/1069963955092606976/1181290110432583811

**Comment by SoulMuncher** [comment]
May be related to another issue I've seen where moving a spell to a different location on the hotbar can cause the spell to appear twice, and the spell will reappear on the hotbar a couple more times in the old location if left empty.

**Comment by jdoleary** [comment]
> May be related to another issue I've seen where moving a spell to a different location on the hotbar can cause the spell to appear twice, and the spell will reappear on the hotbar a couple more times in the old location if left empty.

I haven't seen that since very early days of development, how often does this occur? Are you able to repro?

**Comment by SoulMuncher** [comment]
It happens fairly often... maybe every playthrough or two? Definitely seen it a few times on steam version 1.25. I've never been able to repro it intentionally.

**Comment by SoulMuncher** [comment]
Related: #172 

May have to do with multiplayer sync

**Comment by jdoleary** [comment]
Yes #172 and also 
Note to self: one player ending their turn while the other player is rearranging can do it as we discovered during our playtest
The solution to #43 should fix this too

**Comment by jdoleary** [comment]
Replaced by #188
