### ISSUE TITLE
Old Timemason

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#191]
> SneakyMinion — Yesterday at 6:26 PM
> I really liked the old time mason and while I can see the appeal of the mana-based varient for others, I wish there was still a place for the old.
> 
> all I wished prior to the witch update for was for there to be a way to volunteerly speed up the conversion so you don't have to wait minutes at a time in the late game
> Jordan - Spellmasons Creator — Yesterday at 6:28 PM
> Can you tell me more about the experience of the old that you liked better?
> 
> My intent with the change is to encourange more challenging, fast-paced play, whereas the old - to me - seemed to encourage waiting
> SneakyMinion — Today at 2:39 AM
> I like that it rewarded ultra-fast thinking with the ability to do very powerful spell-combos at the risk of killing yourself (and not just because you actually go down to 0 yourself).
> 
> sure, you could just go quickly (as the current version rewards that behavior), but often the best option (or at least the most fun) involves quickly comparing your options while including the health-to-mana calculation and skating along the edge of death at 5% health.
> 
> yeah, alot of the time you gotta wait because that edge-of-death/glass-canon move involves going to near-death, but its super rewarding (in the endorphins sense) to feel like you found exactly the right combo in just the nick of time to pull it off without killing yourself. 
> As a example:
> I had one run where I killed a bunch of enemies and rezed some corpses with a single spell, only to die half way though the spell as the game lagged---but by coincidence I had targeted myself as well with the rez-heal-portion of the spell.
> unfortunately, because of the lag I quit before I realized the potential of a accidental self-rez.
> (that said, this was before the update that let you self-target with the rez; so I'm not sure this would have worked).
> 
> point is, imagine if that combo worked 
>

**Comment by Couls** [comment]
Maybe a combination of losing health and gaining max mana each turn combined with an option to sacrifice health for mana would work for this player? As a different kind of mason like the idea of exchange and being able to self res would be a possible tactic if you do lose health each turn consistently for example

**Comment by jdoleary** [comment]
Yeah there's a lot of good possibility space here! I will definitely revisit all these ideas and those in the thread when runes are implemented.
https://discord.com/channels/1032294536640200766/1186087113079406612/1186087125997858896
