### ISSUE TITLE
New Art Opportunity

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#192]
My Ideas so far for new art

> Runes System (Suggested by many community memebers)
> The Runes System will be an evolution of the classes system.  It will include all the aspects of the classes system, but be more dynamic since you can have multiple runes at once
> 
> New Spells
> Target Injured
> Spell  Trap
> Target Curse
> Paperweight / Heavyweight (Spells that effect the unit's mass which determines how much impact movement spells have on them.  Suggested by @enigmaticbacon )
> 
> New Features
> Auras
> A class of spells that leaves a persistant aura on the ground or following a unit that has an effect for units inside the aura.
> Momentum
> Momentum is generated when you move either by walking or via spells and can be consumed for devastating use in spells
> Armor (Suggested by @VinnickTalberot )
> Some enemies will be armored which gives them a damage reduction to certain types of spells
> Under certain circumstances, the Spellmason may also gain armor
> 
> New Enemies
> Squid
> Bone Golem

**Comment by SoulMuncher** [comment]
It might be a good idea to have a few generic/reusable rune icons instead of making new art for each one. Maybe major runes get special art and minor runes choose one of X generic looking ones based on function/theme.

**Comment by jdoleary** [comment]
Closed as duplicate.  See milestone: https://github.com/jdoleary/Spellmasons/milestone/4 for individual issues
