### ISSUE TITLE
Improve difficulty button UI

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#20]
SoulMuncher:
In my experience, when making a multiplayer game, the difficulty buttons feel kind've buggy/unclear, and tend to mess with the UI in unexpected ways. It doesn't give good visual feedback and I'm not actually sure if they work or not. I tend to avoid clicking on any extra buttons when making a game now 😅

**Comment by jdoleary** [comment]
https://discord.com/channels/1032294536640200766/1069963955092606976/1185340886402473994

**Comment by SoulMuncher** [comment]
Addition: When making a LAN game or custom server, messing with the difficulty options will take you to the community server screen.
