### ISSUE TITLE
Fix inactivity disconnect

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#22]
> Reported by SoulMuncher:
> My teamate and I loaded into a level, and were talking about possible strategies before placing our characters. We were disconnected due to 1 minute inactivity (not a huge fan of this feature honestly). Anyway, when we reconnected, all of the minibosses had been converted to normal enemies. Priest minibosses that previously had 120 health (iirc) were down to 40 health, and appeared to be normal priest size. When selected, all of the data lined up with a basic priest, but their name was still Priest Miniboss. I should have taken a screenshot

I think what happened here is that the server tries to clean up games where all players have disconnected after a timeout (to see if they'll rejoin) but there must be a bug where it doesn't consider unspawned players as connected.  This should be fixed so only games with actually no clients connected get cleaned up.
I've also noticed in the server-hub that games seem to stick around for WAY longer than I'm expecting them to with no clients.

**Comment by jdoleary** [comment]
@SoulMuncher, you mentioned that this occurs when waiting to choose spawn for over a minute but I have been unable to reproduce.  I've only tried with a local server though.  Maybe it's only on the community servers.  If you have a way to consistently reproduce this please let me know.

**Comment by SoulMuncher** [comment]
If you want, we could try to repro it tomorrow with dev tools open
