### ISSUE TITLE
Dash to a pickup caused a desycn

### ISSUE THREAD

**Issue by jordan-octavia-blue** [jdoleary/Spellmasons#24]
sync: Syncing pickups Array(3)0: "0:false"1: "1:false"2: "2:false"length: 3[[Prototype]]: Array(0) current pickups: Array(4)0: "0:false"1: "1:false"2: "2:false"3: "3:false"length: 4[[Prototype]]: Array(0)
Underworld.ts:3779 sync: Remove excess pickups
Underworld.ts:639 Guard against infinite loop, unit tried to move but it was not its turn.  Clearing stamina
Underworld.ts:881 Attempted to aquire queued pickup via timeout but pickup is undefined

**Comment by jdoleary** [comment]
syncPickups is causing problems because of how it ignores id and just assigns the pickup properties
