### ISSUE TITLE
Explosive Urn pushes enemies way further than predicted

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#244]

**Comment by jdoleary** [comment]
Only on multiplayer.
This happens because server calculates force move immediately and fully and then sends SYNC_SOME_STATE

**Comment by jdoleary** [comment]
Might be the answer to sync after all players end turn instead of syncing after spell

**Comment by jdoleary** [comment]
underworld.awaitForceMoves only awaits on headless.  This is why it's not awaiting the explosion
