### ISSUE TITLE
Two priests can target the same corpse

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#247]
The unit will only be revived once, but both priests spend mana. Also prevents the extra priests from reviving other units

**Comment by jdoleary** [comment]
Maybe we can insta-set them to 'alive' before the animation plays so that when it's looping through priest behavior, the next priest in line won't target them.
That would probably work so long as alive is set before anything is awaited in the priest's action.

**Comment by SoulMuncher** [comment]
Targets are already set and cached in executeNPCTurn before any actions are called. This feels like an issue for the AI refactor
