### ISSUE TITLE
Upgrade spell: Displace

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#25]
To allow for teleporting anywhere

credit: meme_man

**Comment by jdoleary** [comment]
Jordan - Spellmasons Creator — Today at 11:23 AM
This, now that i'm thinking of it, would actually be a little hard to code since I don't have current way in my game engine to make 2 stage spells where you click twice

Maybe there should just be a self-teleport spell

**Comment by jdoleary** [comment]
Note: Upgrades are spells like "Greater Slash" that require a previous spell to be chosen.

**Comment by jdoleary** [comment]
> VinnickTalberot — Today at 3:41 PM
> I think it could be interesting to have a spell that creates a blue portal at your location and one at the target location. Similar in ways to the dash spell. Maybe an upgraded version could do something similar to what the deathmason does, spawning portals around the battlefield.
> I think movement manipulation also becomes very lackluster after the first few levels because the enemies have so much range (for the most part) that it becomes obsolete

**Comment by SoulMuncher** [comment]
See: Mark + Recall in lots of games

Also, maybe teleport just moves you where you click, so you have to have some decent cast range to benefit.
