### ISSUE TITLE
Freeze Return

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#259]
Freeze having a "skip turn" return for onTurnStart seems a little strange, would it make more sense to just check for it in the basic Unit functions that it affects, like getUnitAttackTargets and stuff? 

#161

**Comment by jdoleary** [comment]
It's best not to have spell specific logic anywhere but in the spell's own file.

**Comment by SoulMuncher** [comment]
> It's best not to have spell specific logic anywhere but in the spell's own file.

Yes, this was kind've the main point of the issue: Currently we have to check for a freeze return in several places, instead of imbedding it within the spell/behavior it affects. Lets talk about it on our call in a bit
