### ISSUE TITLE
Upgraded bloat that removes corpses

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#272]
> Ry — Today at 6:37 AM
> as a performance thing
> having an upgraded bloat that deletes the enemy corpse as a garbage collector for the game engine would be huge for necromancer runs too

**Comment by jdoleary** [comment]
> Ry — Today at 6:45 AM
> yepper
> it would add a lot of depth instead of "is my plus up" to make it fit
> plus or stacking whatever they had yknow 2x cones etc or more circle aoe
> like until get to the point where stack circles and plus until it doesn't matter lol 
> Jordan - Spellmasons Creator — Today at 6:46 AM
> The tricky part is if a spell is multi-stage how would that work with stacking.  Like if you could choose the direction of cone, and you had multiple cone with other spells inbetween, then would you have to click a bunch of times to just cast the one spell?
> Maybe there could be a spell that influences the direction for the entire thing - someone else suggested that recently
> Ry — Today at 6:47 AM
> my mind immediately goes to the ping system how you place a little star down
> "beacons" and they either repel or attract directional towards them
> and you bind cones, columns to face them (attract) or repel (face away from) 
> so functionality ingame would be
> click cone
> click beacon option on map
> that cone faces that becon
> column
> beacon action

**Comment by SoulMuncher** [comment]
I don't really get/like this idea.

How else does it differ from bone shrapnel or from regular bloat, and what does it add to the game?

**Comment by jdoleary** [comment]
It could do more damage at the cost of not being able to use the corpse later for resurrect or whatever.
Bone shrapnel is new and doesn't exist in 1.26
