### ISSUE TITLE
Huge Enemy Desync Issues

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#291]
Most enemies don't seem synced very well at all. This is especially noticeable when you have summons. They'll hit something that's really low health, it doesn't die, and then it syncs later once a turn has ended or spell is cast and suddenly the unit is dead (or sometimes back to life). This also means attention markers are frequently wrong and you can target things with spells you shouldn't be able to

**Comment by SoulMuncher** [comment]
Did a little more testing: it definitely seems like enemy attacks are not fully awaited. This may also be the cause of #255

**Comment by jdoleary** [comment]
Which enemy types? All? or a select few?

**Comment by SoulMuncher** [comment]
All iirc. In one really bad instance I had a bunch of dark priests and golems on my side, they killed a bunch of enemies, and then those enenmies were alive again on their turn and attacked me/my summons

**Comment by jdoleary** [comment]
Reproduced: Dark Priests only await their first attack

**Comment by jdoleary** [comment]
Left to test: ancient, ghost archer

**Comment by jdoleary** [comment]
Blood archer seems to move on server but not on local

**Comment by jdoleary** [comment]
Green glop disappears

**Comment by jdoleary** [comment]
Either units have a path and are out of stamina or vice verse but blood archer and green glop are still moving

jtest not move unit archer 300 false
jtest not move unit glop 300 false
jtest not move unit poisoner 300 false
jtest not move unit vampire 0 true
jtest not move unit Blood Golem 0 true

**Comment by jdoleary** [comment]
Fully resolved in ad4e686
