### ISSUE TITLE
Game Lock on Load

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#292]
Played through until level 1+, saved before the second wave of enemies. Quit, played another game for a couple levels, went back to load the old save, the game locks with "loading" and Error: Failed to load game popup. All singleplayer

> Setup: Creating new underworld
Cannot sync inventory, globalThis.player is undefined (index.0acb8c75.js:1)
...
syncTurnMessage: phase: PlayerTurns
Attempted to load a game with no globalThis.clientId (index.0acb8c75.js:1)

**Comment by SoulMuncher** [comment]
Related: #305

**Comment by jdoleary** [comment]
Reproducable:
- make a new game and save
- quit current game
- load that game
- see that game is locked due to globalThis.clientId being an emptystring
