### ISSUE TITLE
Vec2 Object Conversion - Target Similar

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#299]
> @BrewBreuw
when casting the "target similar" spell on an enemy that is standing on top of an item (such as a potion), the spell doubles in potency.

This is an issue with how objects are found via coordinates. It's probably not a good idea to find objects via coordinates, but if it's unavoidable, we should make the checks require more accuracy, and potentially require _exact_ coordinate matching @jdoleary 

I assume it doesn't do this currently due to some desync/rounding issue?

Nevermind. Only planning view does this. This was another issue with the targets list being changed while target similar is running.

**Comment by SoulMuncher** [comment]
Should be fixed in #307

**Comment by jdoleary** [comment]
Reesolved in #307
