### ISSUE TITLE
multiplayer picking classes at inconsistent times

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#301]
Moonlighter — Today at 11:02 PM
In a 5 player game, one of our players got to pick their profession at the start of the 2nd level, before the rest of us

**Comment by SoulMuncher** [comment]
related? end turn firing twice sometimes? #321

**Comment by jdoleary** [comment]
Which function? Underworld.endPlayerTurn? I allow sending multiple MessageType.END_TURN messages in case of desync so the game doesn't get stuck.  It should be idempotent as a failsafe

**Comment by SoulMuncher** [comment]
Nothing specific in mind, just a guess/question. :)

**Comment by SoulMuncher** [comment]
Present in 1.28.2

Fresh game, ally was able to choose their class on the second level. We were both character level 2, exp 2/3, impossible difficulty. I was able to choose my mage type after killing another unit

**Comment by SoulMuncher** [comment]
merged with 718
