### ISSUE TITLE
What happens if you use `bone shrapnel` on an ally player unit

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#306]
will it break for next level because it cleans them up?

**Comment by SoulMuncher** [comment]
@jdoleary just tested in hotseat: it breaks pretty bad. Player has no image/id/etc. on the next level.

We could ignore players in bone shrapnel targeting, or we could implement a partial cleanup/corpse removal function that has an exception for the player, that way they can still use it on themselves/allies without breaking the game.

**Comment by jdoleary** [comment]
Related #310 

@SoulMuncher  agreed, we need to handle player unit cleanup safely in the cleanup function itself so that this is no longer a footgun in any spell that uses it.  I'll take this one

**Comment by jdoleary** [comment]
Fixing #310 will close this
