### ISSUE TITLE
clear level and end up with no stamina

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#316]
Setup:
- multiplayer game
- Kill the final enemy and one of the ally players at the same time (I used an explosive barrel)
- See that the portals appear but you have no stamina

bug: you have to end your turn twice to get stamina to go through the portal instead of having infinite stamina like you should

**Comment by SoulMuncher** [comment]
Note to self: Can be reproduced without an ally player

**Comment by jdoleary** [comment]
Note: Stamina is actually being set to `null` somehow

**Comment by jdoleary** [comment]
Stamina is null inside of SYNC_SOME_STATE message

**Comment by jdoleary** [comment]
To reproduce, one player has to be dead when the other player finishes the level

**Comment by SoulMuncher** [comment]
> To reproduce, one player has to be dead when the other player finishes the level
I'm also able to reproduce this every turn when only one player is in the headless lobby/game.
