### ISSUE TITLE
Test Remote Play Together for the next sale

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#318]

**Comment by jdoleary** [comment]
@SoulMuncher I'll need your help with this.  The next big sale is a Remote Play Together sale and I've had some players report that they've had problems getting Spellmasons to work with Remote Play Together.  So this should be a priority after 1.27 is released.

**Comment by jdoleary** [comment]
In a recent commit I added the ability to Shift Tab in game to bring up the friends list.  This only works via the exe, so I'll make a new beta version and we'll have to test it to make sure it works well.

**Comment by SoulMuncher** [comment]
> In a recent commit I added the ability to Shift Tab in game to bring up the friends list. This only works via the exe, so I'll make a new beta version and we'll have to test it to make sure it works well.

```
globalThis.addEventListener('keydown', event => {
  if (event.code == 'F12' && globalThis.electronSettings) {
    // @ts-ignore
    globalThis.electronSettings.toggleDevTools();
  } else if (globalThis.steamworks && event.code == 'Tab' && event.shiftKey) {
    globalThis.steamworks.shiftTab();
  }
})
```

This won't account for anyone who's changed their steam overlay keybinds (such as myself). Would there be any way to access that keybind information via the API? Also, are we implementing all of this Steamworks support manually? I am concerned that this will result in very limited steam integration/support 😅

**Comment by SoulMuncher** [comment]
> @jdoleary
In a recent commit I added the ability to Shift Tab in game to bring up the friends list. This only works via the exe, so I'll make a new beta version and we'll have to test it to make sure it works well.

```
globalThis.addEventListener('keydown', event => {
  if (event.code == 'F12' && globalThis.electronSettings) {
    // @ts-ignore
    globalThis.electronSettings.toggleDevTools();
  } else if (globalThis.steamworks && event.code == 'Tab' && event.shiftKey) {
    globalThis.steamworks.shiftTab();
  }
})
```

This won't account for anyone who's changed their steam overlay keybinds (such as myself). Would there be any way to access that keybind information via the API? Also, are we implementing all of this Steamworks support manually? I am concerned that this will result in very limited steam integration/support 😅

**Comment by jdoleary** [comment]
It is unfortunately going to be very limited.  I can't get the steamworks API to work with electron.js.  I'm not sure if I can find the overlay keybinds, I'll have to check.  What did you set yours to out of curiosity?

**Comment by SoulMuncher** [comment]
I've rebound mine to Shift + F1, because there were several games where I'd push Shift+Tab to do certain actions, such as sprinting and looking at an overlay map/scoreboard/inventory simultaneously, but then it'd just pull up the Steam overlay, lol.
