### ISSUE TITLE
CLIENT_SEND_PLAYER_TO_SERVER property desync: property:endedTurn, host:true, client:false

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#319]
Address this, maybe host should have control over endedTurn.  Maybe this is how they got stuck?

**Comment by SoulMuncher** [comment]
>Address this, maybe host should have control over endedTurn.

Giving the host full control over certain things such as setting turn phases sounds interesting. Is there anywhere that this happens currently?
