### ISSUE TITLE
Toxic Res + Clone == death?

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#323]
> Kosmic Horror — Today at 3:39 PM
> Last night my friend and I were running up against the final boss on first loop 0. He casts Toxic Revive (might be misremembering the spell name, revives enemies with 3 turns until they died) on a large group of corpses. I cast clone on that group. The entire group just splattered instead of getting cloned. It may be because there were already a lot of enemies on the screen and that's a memory/overflow safeguard? But if so, it'd be nice if there was a warning since that very nearly destroyed our run

**Comment by SoulMuncher** [comment]
No repro found. This might've been a weird desync issue
