### ISSUE TITLE
When I cast and then move my player jumps back to cast location

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#329]

**Comment by jdoleary** [comment]
For arrow spells only

**Comment by SoulMuncher** [comment]
I was able to repro this with poison as well, it may affect all spells, though I only see the bug in multiplayer.

**Comment by jdoleary** [comment]
Just poison in the spell stack?  I haven't been able to reproduce it consistently so maybe the root cause only happens occasionally.

**Comment by SoulMuncher** [comment]
> Just poison in the spell stack? I haven't been able to reproduce it consistently so maybe the root cause only happens occasionally.

I think so. I didn't catch a recording unfortunately.

**Comment by jdoleary** [comment]
Note: Always reproducible on multiplayer.  Use a long arrow spell and move after casting.

**Comment by jdoleary** [comment]
Note: Player unit movement runs immediately on the local client but synchronously on server and others so that the player doesn't have a laggy movement experience for their own unit.
See eventListeners.ts useMousePosition() / line 524 and line 536

**Comment by jdoleary** [comment]
```
networkHandler.ts:480 jtest start processing SPELL
networkHandler.ts:913 jtest finished handling SPELL
networkHandler.ts:480 jtest start processing MOVE_PLAYER
networkHandler.ts:913 jtest finished handling MOVE_PLAYER
networkHandler.ts:480 jtest start processing MOVE_PLAYER
networkHandler.ts:913 jtest finished handling MOVE_PLAYER
networkHandler.ts:480 jtest start processing MOVE_PLAYER
networkHandler.ts:913 jtest finished handling MOVE_PLAYER
networkHandler.ts:480 jtest start processing MOVE_PLAYER
networkHandler.ts:913 jtest finished handling MOVE_PLAYER
networkHandler.ts:480 jtest start processing SET_PLAYER_POSITION
networkHandler.ts:913 jtest finished handling SET_PLAYER_POSITION
networkHandler.ts:480 jtest start processing MOVE_PLAYER
networkHandler.ts:913 jtest finished handling MOVE_PLAYER
networkHandler.ts:480 jtest start processing SYNC_SOME_STATE
networkHandler.ts:913 jtest finished handling SYNC_SOME_STATE
```
