### ISSUE TITLE
Health Potion removes overcapped HP

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#346]
> @ MilkToast
I had around 7,000/200 health along with blood curse. I ran into a health pot, and ended up with only 170/200. It seems like the blood curse damage took health away starting from my max health rather than current health. This might be intentional, but I figured I'd post it anyway. No screenshots sorry...

See Pickup.ts line 868
`player.unit.health = Math.min(player.unit.health, player.unit.healthMax);`

**Comment by jdoleary** [comment]
Okay, we just have to make sure that health potions don't go over max but also don't cap it. I think this is already done in `heal` so maybe we extract that logic to a function
