### ISSUE TITLE
Turn Phase Refactor

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#362]
Currently working on a large refactor centered around turn phases.

The goal is to solve the issues below and reduce the frequency of similar issues in the future, as well as prevent the game from locking under unusual circumstances.

#206
#256
#290
#300
#301
#316
#319
#321
#343
#354
#357
#404

**Comment by jdoleary** [comment]
I found an event log https://server-hub-d2b2v.ondigitalocean.app/events?archive=spellmasons-events/Walrus-SF-Mon,%2015%20Jan%202024%2021:16:36%20GMT-default-0.5737929421069852-1705364261895.json
Where at the bottom a bunch of setPhase messages occurred, they went 2,3,1,2,2,3,1,2,2,3,1.  Which seems unusual.  May be useful to this refactor.
