### ISSUE TITLE
Health/Mana bar predictions

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#39]
The ui bar for health and mana doesn't always display the predicted outcome. Note: this becomes extra apparent with the new send-mana blessing.

Ex. Healing an enemy unit, Conserving enemy mana (Conserve seems particularly weird, as it causes the mana bar to flicker when prediction recalculates)

**Comment by jdoleary** [comment]
This one will be tricky.  Take a look at src/graphics/PlanningView.ts's runPredictions function and more specifically Unit.syncPlayerHealthManaUI() in src/entity/Unit.ts. It updates the UI with the values of the prediction copy of the player unit.

**Comment by SoulMuncher** [comment]
This should be mostly resolved with #146 

Conserve still flickers a little

**Comment by SoulMuncher** [comment]
This should be mostly resolved with #146 

Conserve still flickers a little, might make this a new issue
