### ISSUE TITLE
Way to ping Discord members who are looking for group

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#390]
> Nautilus
> OP
>  — Today at 9:41 PM
> Oh also not necessarily game related but adding a role on the discord that allows pinging specifically players who want to play with a group would be nice :)

**Comment by SoulMuncher** [comment]
I did some community management for the Wands VR Discord server while I worked at Cortopia (I actually still do most of the server management), and I would love to set this up as a self-assignable role, ping roles for game announcements and similar, potentially setup things like server onboarding to direct newcomers to the right place and automod to handle obvious troublemakers and stuff like that. Let me know if you're interested, it wouldn't take long at all 😄
