### ISSUE TITLE
Server Crash: Arrows

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#399]
https://steamcommunity.com/app/1618380/discussions/0/7091547412719649496/

**Comment by SoulMuncher** [comment]
Was able to reproduce some weird behaviour a couple minutes ago on the Europe server.

I used super me and then spammed a ton of arrows on the first level, and eventually my player character disappeared. These are the longs I'm seeing

![1](https://github.com/jdoleary/Spellmasons/assets/68413161/2d9eec0b-c51f-4a7b-91be-4355c2cd3141)
![2](https://github.com/jdoleary/Spellmasons/assets/68413161/e5e11c8e-dbcf-434a-bbdb-2e43eee32c62)

**Comment by SoulMuncher** [comment]
I may have run into the portal at some point while arrow messages were processing, and it didn't trigger the portal movement until the messages had caught up, at which point it took me to the next level and the game proceeded as normal. Going to keep investigating

**Comment by SoulMuncher** [comment]
Also noticing some delay when I enter a portal now, which leads to many enter-portal messages being sent in a row:

![3](https://github.com/jdoleary/Spellmasons/assets/68413161/d14d33ec-f109-4ad0-8ba0-c6199b4500c2)
