### ISSUE TITLE
Desync can cause Minibosses to revert sprite size

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#405]
Noticed a desync on the current steam version which caused a miniboss priest to become the size of a normal priest.

Happened on Europe Community Server (playing alone) on Jan 19 when testing an arrow issue

related:
- #42
- #638

**Comment by jdoleary** [comment]
Hmm, the load function should have fixed the size, was the miniboss boolean set to false too or just the image size changed?

**Comment by SoulMuncher** [comment]
I'm not sure if the miniboss boolean was changed.

If it helps: It happened in the middle of my turn. The unit still had miniboss stats and it said "Priest Miniboss" in the tooltip, but the sprite size was changed to default.

**Comment by SoulMuncher** [comment]
Combining with #638
