### ISSUE TITLE
Slash is not Awaited Correctly

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#407]
(Note: video is sped up by 10% due to issue file size limits)

https://github.com/jdoleary/Spellmasons/assets/68413161/2f263995-253b-445d-9b8a-8018913d71e1

**Comment by SoulMuncher** [comment]
The game will also have to wait for a long timeout if the Slash is refunded (ex. due to targeting a pickup)

**Comment by jdoleary** [comment]
@SoulMuncher This has been fixed, can you please verify?

**Comment by SoulMuncher** [comment]
Re-opening because we forgot to fix heavy and mega slash too lol
