### ISSUE TITLE
Keyboard camera stuck moving

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#411]
Innonminate
OP
 — Yesterday at 6:06 PM
When I move around the field using the w, a, s, d buttons, sometimes the camera just starts moving endlessly in one direction. I can still return to my character using the Z button or use the opposite button and then use the middle mouse button to return to the field if I didn't land before this error occurred. It's just annoying. I'll try to repeat this in a single player game tomorrow to find out if this bug only appears in multiplayer or not.

**Comment by SoulMuncher** [comment]
Happens in single and multiplayer

Consistent Repro:
- Start holding a movement key
- Start holding alt
- Let go of movement key
- Let go of alt
- Observe endless camera movement

**Comment by SoulMuncher** [comment]
All modifier keys seem to block several game actions, namely in handleInputDown() and handleInputUp()
The additional modifier key causes the event name to change, so when we evaluate == 'someEventName', the evaluation returns false

You cannot move camera at all while holding shift/ctrl/alt
