### ISSUE TITLE
Change Discord server to Community server

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#414]
- [x] Change Announcement channel to an actual "announcement" channel so it's followable

**Comment by SoulMuncher** [comment]
> Onboarding is set up, Announcements channels are now followable, several roles including LFG are now self-assignable (can easily add more roles, feel free to request/share ideas. I think one for community events/polls could be cool). I also combined the two moderator channels and the two lfg channels into one channel each to prevent channel crowding. The onboarding process also had me make a slightly more comprehensive rules list. Lastly, I took the old readonly bug reports/suggestions channels channel and put them in their own category way at the bottom called "Archive", which users can opt in to after the onboaridng process if they want to, but otherwise won't take up space. Should help direct people to the right channels and stuff :)

> We can't apply for "Discovery" yet, as you need at least 1000 members and a certain activity level, but Spellmasons is officially a community server now, so that's good.

**Comment by SoulMuncher** [comment]
#390
