### ISSUE TITLE
F12 Doesn't work in Master / Localhost Browser

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#415]
- Start Singleplayer game
- Place character
- Press F12
- Developer window does not appear

**Comment by jdoleary** [comment]
Which version is this in? It's working for me in Current live build and on dev

**Comment by SoulMuncher** [comment]
(Edited repro steps for clarity)

This was on the current master branch in Microsoft Edge, but let me double check, maybe I missed something 🤔

**Comment by jdoleary** [comment]
Okay I am now reproducing this on my end, i was up to date with origin/master

**Comment by jdoleary** [comment]
I think it may be due to 9eb34ed7

**Comment by SoulMuncher** [comment]
Okay, I'll look into it!
