### ISSUE TITLE
Idea: 'Shatter Potion" - You can damage potions to break them

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#416]
You can damage potions to break them, which could have some interesting effects:

It could add a special effect to water/liquid, such as healing, additional mana regen, or 0 stamina cost movement
It could apply the potion effect to all units in a small radius
Other ideas?

**Comment by jdoleary** [comment]
I love this idea, what if it applies the potion to units in a radius?

**Comment by jdoleary** [comment]
Let's add it to 1.28, this is a great synergy

**Comment by SoulMuncher** [comment]
The more I think about this, the more I'm not sure it's a good idea 😅 I was playing a game yesterday kind've thinking about how it'd play out if I could damage potions, and most of the time it went something like this:
- A bunch of aoe targeting spells > A bunch of enemy units standing near targeted potions > Oh wow that change would suck, I'd either have to heal everything or not be able to cast this spell

It seems real tricky/tedious to implement code-wise as well. We'd have to account for it in so many different spells' targeting behaviour and setup a way to make pickups damageable and stuff like that.
Maybe if the mechanic was tied to a specific spell? I don't know...

**Comment by SoulMuncher** [comment]
> Spell Name: "Shatter Potion"

**Comment by SoulMuncher** [comment]
Still needs art/animation/fx before next update
