### ISSUE TITLE
Rejoined empty games may have minibosses reverted to regular size

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#42]
Splitting this particular issue off from #22.  The disconnect has been fixed but there may still be an issue where rejoining a game (or maybe even loading a game) on a level with minibosses causes the minibosses to be "halfway" reverted to normal enemies.

See https://github.com/jdoleary/Spellmasons/issues/22#issuecomment-1842050899 for details

**Comment by SoulMuncher** [comment]
Possibly related: https://github.com/jdoleary/Spellmasons/issues/638

Outdated issue.
