### ISSUE TITLE
Summon Cards disappearing

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#43]
> RainbowLuck — Yesterday at 4:45 PM when u capture soul to set up a game and u
> got kick out and you come back with no soul is realy frustrating '-'
> 
>     timothycombs12 — Yesterday at 8:40 PM
>     found a glitch. target arrow + slash + capture soul targeting an ancient. it will refund the spell and not take hp from the player, but it will not give a spawnable ancient. i dont know if the last part is on purpose

Some players are reporting that their summon cards are disappearing.  Probably a sync issue

**Comment by jdoleary** [comment]
Note to self, Player Sync should never overwrite the client's player's inventory.  Maybe add a `soft` flag to syncing so LOAD can fully overwrite but turn-by-turn Player Sync wont

**Comment by jdoleary** [comment]
Replaced by #188

**Comment by SoulMuncher** [comment]
Reported again:

> old_man — Today at 1:07 AM
This has happened to me a couple times - playing as necro I don't get any of the summons in my spellbook - is that a known issue?

**Comment by jdoleary** [comment]
Shit,  I'm really not sure what's causing this.  Maybe there's a SET_PHASE being sent before it gets added or something? I even added logic in this update to make sure the server doesn't overwrite the local player.

**Comment by jdoleary** [comment]
Okay this *may* be because it's not obvious enough that you can scroll in your spellbook.  If you look at the screenshot, he hasn't scrolled down.  I asked to see if this is indeed what happened.
If so, we'll need to add obvious UI to show that you can scroll.  This is definitely my fault, it's not obvious enough.

**Comment by jdoleary** [comment]
Probably due to `Cannot capture soul, upgrade not found` error, logged a total of 16 times

**Comment by jdoleary** [comment]
![image](https://github.com/jdoleary/Spellmasons/assets/6413317/a88bdeb8-2d10-4573-8ee8-cdbb2d212413)

**Comment by jdoleary** [comment]
Looks like somehow freeSpells is not being synced to the host:
<img width="267" alt="image" src="https://github.com/jdoleary/Spellmasons/assets/6413317/88f31baa-9f1c-4e87-857c-760002b39006">
