### ISSUE TITLE
Deathmason Cinematic only plays the first time

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#431]
I am not seeing the cinematic after the first encounter:
- Start game
- 'Skip to Deathmason level'
- 'Super me' (so you don't die) and end turn
- See cinematic
- Quit to main menu
- Repeat
- No cinematic

**Comment by jdoleary** [comment]
Resolved
https://github.com/jdoleary/Spellmasons/commit/c8a4d6f7b5659063c243c86e16d0322783e348c8
