### ISSUE TITLE
Multiplayer: 0 stamina after portal following position desync of other player

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#440]
Using the admin tool: `Test: Induce server desync - selected unit position to NaN, NaN'`
In a 2 player multiplayer game (headless, not hotseat).  I desynced Player1 to NaN, Nan
Player 2 cast a spell syncing Player1's position to appear at 0,0
I ended my turn and Player1 disappeared on both screens.
I beat the level with Player2, a portal appeared but I had 0 stamina
I ended my turn again and the level progressed.

The good: I didn't get stuck, I was able to get through just by ending my turn.
The bad: Somehow I had 0 stamina, and on the player that didn't desync, so I'm not sure where that came from.

Ideal fix: Players should never have 0 stamina after the portals have spawned.
Overall this is not a huge deal though since I didn't get hardlocked, but it could still be a bad experience for players who don't try ending their turn a few times.

**Comment by SoulMuncher** [comment]
I'm not exactly sure what causes the 0 stamina issue, but it's very common in headless multiplayer even without desyncs.
It happens more often than not in my experience.

I haven't seen it happen in singleplayer/hotseat.

**Comment by jdoleary** [comment]
Yes position desync worked as expected.  I'll close this as a duplicate of #316
