### ISSUE TITLE
Hand crafted maps

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#454]
The randomly generated maps leave a lot to be desired, maybe hand-crafted maps would have more character, or we could do a combination.

**Comment by SoulMuncher** [comment]
I'm a big fan of using handmade prefabs in a room/exit style level generation system. Worth looking into, may not be the best option for more open/organic areas

**Comment by jdoleary** [comment]
Yeah I'm open to discussion on this.  I've tried 4 different times to make a room generation algorithm that feels meaningfully unique and I'd say I've failed every time.  One of the complexities is how liquid works.  It needs to be surrounded by special tiles (borders, corners) which has made conventional level gen algorithms really hard.  Maybe I should try wave function collapse again.

**Comment by jdoleary** [comment]
Oh right so you're referring to like "Binding of Isaac" style room gen.  That could be interesting.

**Comment by SoulMuncher** [comment]
> Oh right so you're referring to like "Binding of Isaac" style room gen.  That could be interesting, they'd have to be a lot larger though

Um not really. I don't think so anyway, I'm not very familiar with Binding of Isaac's level gen.

To describe in more detail, you would have premade "rooms", and these could be however big or small you want and whatever shape you want. You would build each individual room by hand, placing water/tiles/etc. They could be literal rooms, segments of a cave, or even just an open field with a lake in the middle.

Each room should have a definable boundary, to prevent overlap during generation, at least  one "entrance" or point to generate the room from, and unless you want it to be a dead end, an exit to generate more rooms off of it. There can be as many exits as you like. If a room is unable to generate from a certain exit, that exit will be filled with some kind of dead end object during level gen (this can be a locked door, a wall, some rocks, etc.) 

Each room can have a tag or list of tags, essentially stating what that room is, and exits with a list of tags that could be generated going off of them. This can be used for many things, such as ensuring different entry/exit types (door transition vs wide cave transition) match up, and to ensure a certain room type spawns a set number of times and stuff like that.

The generation itself can be tweaked to make a linear dungeon with a main path and limited length "branches" to explore, a sprawling web of rooms with corridors between, and even open world landscapes similar to diablo/path of exile. It's incredibly versatile and I'm confident it could make some awesome maps. My only concern is figuring out how we would make and store these rooms in typescript, but maybe you have some ideas?

If you want to hop in a call some time I have some older projects that use this form of level generation and I could show you what it looks like in practice (though it would be in Unity)

**Comment by SoulMuncher** [comment]
Note: This would work with liquids and all of that as well, since you would be placing them by hand in the prebuilt rooms
