### ISSUE TITLE
New Spell: Alchemize

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#469]
Converts a potion into a random other potion

**Comment by jdoleary** [comment]
I like the idea of making it deterministic.
Also we should add more potions (especially now that we have Potion Shatter).
I'm thinking
- Poison potion
- Purify potion
- Resurrect potion
Any other ideas?

I can easily vary the colors on existing potions with a shader

**Comment by SoulMuncher** [comment]
@jdoleary 
Idea: Maybe alchemize could have a separate "helpful" and "harmful" potion table that it loops through depending on the target, and then you can turn the potions into their counterpart via purify/poison ? This would prevent really long deterministic cycles and also encourage some creativity.

So good potions stay good: Health Stamina and Mana may cycle through eachother, but will never turn into a poison or cursed mana potion, and vice versa.

**Comment by SoulMuncher** [comment]
> I like the idea of making it deterministic. Also we should add more potions (especially now that we have Potion Shatter). I'm thinking
> 
> * Poison potion
> * Purify potion
> * Resurrect potion
>   Any other ideas?
> 
> I can easily vary the colors on existing potions with a shader

I think that sums it up. Could potentially add these two as well:
- Fortification Potion
- Slowness Poton

Obviously freeze and any other modifiers *could* work, but that might be unnecessary overlap and too many variables (Maybe we would allow them but not spawn them directly into the level? I'm not sure.)

**Actually, here's an idea stemming off that!**
What if there was a "blank" potion of some kind that would absorb the first modifier attached to it, and then later apply that modifier as its potion effect. Summoning this blank potion could also be a spell.

**Comment by jdoleary** [comment]
I love that idea!
One thing we'll need to keep in mind is that some potions only work on players (hp, mana) while some pickups work on any unit (traps).  We'll have to decide which of these should apply to units if any.  Like what good is a poison potion if it can't damage an enemy (other than usage with "potion shatter")?
But then again, right now all potions are only for players so if we change that for some that could be confusing.  Maybe we just use the trap for anything that we want applicable to enemies. 
Like maybe if you use a modifier on a trap is adds that modifier to whoever springs it.  It would certainly make traps more interesting and synergistic.
