### ISSUE TITLE
New Spell: Merge

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#472]
Merges two units together, summing their stats
This will be tricky, how will it interact if used on a Spellmason? Maybe it only impacts current health / mana instead of max?

**Comment by jdoleary** [comment]
Possible problems:
- Spellmasons merging with each other
- Spellmasons merging with units for ridiculous stats

**Comment by Koliostro** [comment]
Can this be used on potions to combine their characteristics?

**Comment by jdoleary** [comment]
> Can this be used on potions to combine their characteristics?

That's a great idea! @SoulMuncher Let's do that too.

Also, merge might be a way to handle folks with computers that can't handle too many units.  It's not my favorite solution, but some get down to 1fps when there's too many units on the screen, so I think maybe auto merging (opt in, in settings or multiplayer game setup) could handle that edge-case
