### ISSUE TITLE
New Spell: Spike Pit

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#479]
(May need art, how is this different from trap)

Deals damage on a unit when they enter or cross through it
We could use "Aura" system for this to differentiate it from the trap Pickup

**Comment by SoulMuncher** [comment]
I imagine the spike pit would also "root" them in place, as if they've fallen onto or been impaled with spikes.

If not, it might make more sense for this to be like a flame circle or something

**Comment by jdoleary** [comment]
I agree, we should save this to use aura tech so it's different from traps
