### ISSUE TITLE
New Spell: Stomp

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#480]
A movement spell that takes all units in a radius around you and thrusts them away

**Comment by SoulMuncher** [comment]
How is this different from shove? More aoe + damage and less push?

**Comment by jdoleary** [comment]
> How is this different from shove? More aoe + damage and less push?

Yes.  I'd like to start to create "melee" type spells - like how arrows are kind of their own sub category, I'd like there to be spells that are all within melee damage.
The cool thing about stomp is that you don't need a targeting spell to go with it, you can just get closer to bad guys and then get them a safe distance away.

**Comment by SoulMuncher** [comment]
Sounds awesome!
