### ISSUE TITLE
GUI Scale options for steamdeck

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#502]
https://discord.com/channels/1032294536640200766/1208089496101593097/1208089496101593097

This is an important UI feature for users playing on steam deck

**Comment by SoulMuncher** [comment]
It should also be noted that the Class selection menu is cut off on PC at any UI scaling above 0.6, and the Spell-Planning-Bar could have smaller margins

**Comment by jdoleary** [comment]
This has been fixed in a recent update with improved auto card scaling
