### ISSUE TITLE
Enemy that consumes corpses

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#518]
Effect: Might heal, grow stronger, summon allies, etc.

Meant to clean up the battlefield and counter passive summoner strategies

**Comment by jdoleary** [comment]
I like this idea

**Comment by jdoleary** [comment]
What if we just add this to Goru's ai state machine?
It's expensive to make new units with all the animations so we could fold this into an existing unit.
Or what about a glop? It could go over a corpse and eat it.  That fits with the character
