### ISSUE TITLE
Clicking off window causes ForceMove RaceTimeout

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#520]
While in the browser, if you move to another tab while an entity is being pushed, it will cause a race timeout.
I'm not sure if this has any effect on the build version. Could an unfocused window cause headless errors/desync?

**Comment by jdoleary** [comment]
I'm pretty sure this doesn't happen in the exe build.  Please try to reproduce in an exe build and close if not

**Comment by SoulMuncher** [comment]
Doesn't occur in .exe build
