### ISSUE TITLE
Spell: Drown Variations

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#539]
1. Damages all units that are submerged wherever they are
2. Huge percentage damage to targeted units submerged

@SoulMuncher thoughts?
I think drown is a rather blah spell atm, these upgrades could make it much more interesting

**Comment by SoulMuncher** [comment]
To inspire further ideas: What if Drown effectively froze the affected unit for a turn, keeping it in the liquid longer, and having some use as a crowd control spell

**Comment by jdoleary** [comment]
I like that idea but I'm not sure it makes sense thematically.  How would we swing that?
Also, Drown ranked F on the community feedback form so we'll need to improve or buff drown itself in addition to variations.

**Comment by SoulMuncher** [comment]
I just kind've imagined the unit struggling to swim. Could go crazy with it and make it more of a "whirlpool" effect or have some partially visible creature attempting to pull/hold the unit in the water. Could have persistent VFX similar to poison, but instead of green acid it's like water splashing around. Lol, maybe that's too graphic. I'm not sure.

**Comment by jdoleary** [comment]
I'd love that I just don't have the budget for more art right now 😭 How about we do blue particles splashing upward for now?

**Comment by jdoleary** [comment]
FYI, new drown icons for upgraded drown are spellIconDrown2.png and spellIconDrown3.png.

My current thoughts about this issue is:
1. Drown itself should be massively buffed.  Maybe like 2x damage from what it is.  It requires that you get units into liquid which isn't always easy so the payoff should be worth it.
2. Let's call the spellIconDrown2.png one "Blood Bath" and have it "Require" drown but not be an "upgrade".
Blood Bath should deal drown damage to all units that are submerged even if they aren't targeted
3. spellIconDrown3.png should be called "Dark Tide" and it should disable movement of units in liquid for 2 turns wherever they are.
It should also be a "Require" of drown and not an "upgrade"

**Comment by SoulMuncher** [comment]
@jdoleary 
Dark Tide sounds really cool! I love it.

For blood bath, I like the idea of it being a target-submerged spell, instead of just dealing damage? More potential for creative combos / emergent gameplay.

**Comment by SoulMuncher** [comment]
I want to be careful with directly buffing drown, it's already a very strong and obvious choice in specific scenarios. Increasing the damage without making it easier to use/set up just makes it a more binary decision when it *is* good, since they're either near liquid or they aren't.
