### ISSUE TITLE
Seashell infinite loop

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#555]
[smms] [2024-03-18 18:21:34] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:21:34] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:21:34] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:21:34] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:21:34] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:24:38] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:24:38] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:24:38] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:24:38] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:24:38] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:27:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:27:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:27:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:27:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:27:48] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:30:52] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:30:52] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:30:52] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:30:52] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:30:52] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:33:59] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:33:59] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:33:59] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:33:59] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:33:59] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:37:08] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:37:08] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:37:08] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:37:08] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:37:08] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:40:14] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:40:14] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:40:14] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:40:14] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:40:14] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:43:26] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:43:26] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:43:26] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:43:26] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:43:26] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:46:30] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:46:30] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:46:30] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:46:30] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:46:30] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:49:37] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:49:37] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:49:37] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:49:37] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:49:37] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:52:43] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:52:43] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:52:43] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:52:43] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:52:43] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:55:47] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:55:47] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:55:47] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:55:47] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:55:47] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 18:58:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:58:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:58:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:58:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 18:58:57] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:01:59] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:01:59] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:01:59] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:01:59] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:01:59] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:05:04] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:05:04] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:05:04] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:05:04] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:05:04] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:08:13] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:08:13] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:08:13] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:08:13] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:08:13] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:11:22] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:11:22] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:11:22] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:11:22] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:11:22] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:14:34] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:14:34] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:14:34] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:14:34] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:14:34] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:17:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:17:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:17:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:17:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:17:48] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:20:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:20:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:20:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:20:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:20:57] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:24:07] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:24:07] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:24:07] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:24:07] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:24:07] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:27:14] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:27:14] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:27:14] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:27:14] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:27:14] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:30:24] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:30:24] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:30:24] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:30:24] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:30:24] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:33:40] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:33:40] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:33:40] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:33:40] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:33:40] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:36:58] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:36:58] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:36:58] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:36:58] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:36:58] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:40:11] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:40:11] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:40:11] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:40:11] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:40:11] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:43:28] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:43:28] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:43:28] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:43:28] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:43:28] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:46:31] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:46:31] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:46:31] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:46:31] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:46:31] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:49:36] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:49:36] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:49:36] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:49:36] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:49:36] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:52:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:52:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:52:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:52:48] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:52:48] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:55:55] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:55:55] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:55:55] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:55:55] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:55:55] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 19:58:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:58:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:58:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:58:57] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 19:58:57] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 20:02:04] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:02:04] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:02:04] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:02:04] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:02:04] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 20:05:08] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:05:08] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:05:08] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:05:08] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:05:08] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 20:08:11] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:08:11] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:08:11] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:08:11] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:08:11] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 20:11:21] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:11:21] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:11:21] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:11:21] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:11:21] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 20:14:26] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:14:26] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:14:26] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:14:26] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:14:26] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 20:17:31] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:17:31] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:17:31] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:17:31] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:17:31] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 20:20:35] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:20:35] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:20:35] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:20:35] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:20:35] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 20:23:41] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:23:41] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:23:41] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:23:41] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:23:41] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 20:26:46] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:26:46] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:26:46] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:26:46] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:26:46] Force return from headless gameloop to prevent infinite loop
[smms] [2024-03-18 20:29:54] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:29:54] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:29:54] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:29:54] _gameLoopHeadless hit limit; stillProcessingUnits Blood Golem
[smms] [2024-03-18 20:29:54] Force return from headless gameloop to prevent infinite loop

**Comment by jdoleary** [comment]
Happened on another server with Spellmason unit

**Comment by jdoleary** [comment]
There must be an infinite loop bug inside of gameLoopUnit.  Maybe we need to add a killswitch

**Comment by SoulMuncher** [comment]
@jdoleary
fixed with https://github.com/jdoleary/Spellmasons/commit/e1bc833469cdaef1f71a599479768770bdb4ab89 ?
