### ISSUE TITLE
Blood Curse + Split = Inf Health

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#565]
@theytookmysoul aka Wisky
https://discord.com/channels/1032294536640200766/1220834579523436628

## My Guess:
**Setup:**
- Decoy has 100 hp
- Blood curse doubles it to 200
- Splits stores 200 as original value and then halves it to 100
- Purify is cast

**Expected:**
- Decoy has 100 hp and no modifiers

**Actual:**
- Blood curse is removed, which divides health by 2, putting it at 50
- Split is removed, which returns health to the stored value, putting it at 200.
- Decoy has 200 hp and no modifiers

**Comment by SoulMuncher** [comment]
A "good enough" fix could be to remove the stat "storing" and just have it multiply/divide like everything else. There will be rounding errors, but maybe that's acceptable

**Comment by jdoleary** [comment]
I feel like there was a reason that it needed to store it which I can't remember.

What if purify made sure to remove them in the order they were added?  Split is a curse too, so if it removed them, split, then blood curse, it would meet the expected critieria

**Comment by SoulMuncher** [comment]
> What if purify made sure to remove them in the order they were added? Split is a curse too, so if it removed them, split, then blood curse, it would meet the expected critieria

I'm not sure how we'd do this cleanly. Especially when considering quantity. A player might inflict split 1, then blood curse, and then split 2 and 3.

> I feel like there was a reason that it needed to store it which I can't remember.

Split was changed to store stats because of rounding errors:
If a unit has 20 hp and splits 3 times, it goes 20>10>5>2 (floor(2.5))
Purifying would then make it go 2>4>8>16

It's not great, but I think it's one of those technical things in the engine and it's better to be consistent with it than to create edge cases like this, imo. Rounding errors are bound to happen when using directly mutable integers as stats, and this might as well be considered the expected behavior / a feature.
