### ISSUE TITLE
When the whole party is frozen in the same turn game endlessly skips turns

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#568]
Waterbending Squirrel
OP
 — Today at 6:09 PM
To replicate bring whole party in one place and use something like Target Circle + Freeze
The game is stuck in endless loop when it says its your turn but you can't move or do any other action, and enemies just permamently attack you.

Note: after being frozen the players that got frozen can't move until someone? does and action. We will test this further and make another bug.

**Comment by SoulMuncher** [comment]
This is likely because of the setTimeout() in onTurnEnd(). The modifier is not immediately being removed, which could cause a headless desync.

**Comment by SoulMuncher** [comment]
Reproduceable without any allies in headless.
