### ISSUE TITLE
Damage as % of Base

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#578]
TL;DR:
Damage bonuses in games are fun, but not easily doable in Spellmasons at the moment. If spells scaled off of the player's damage stat, we would be able to add damage bonuses/penalties to them. This means already existing spells like empower/enfeeble would have a use case on players, and we could create even more new content surrounding damage increases/decreases, which is really nice. Should have a very low time cost.

> @SoulMuncher 03/20/2024 3:33 PM
> Kind've on that topic, I've wondered if spells should take from a core damage stat anyway. Say spellmasons have a base damage of 20 that can be increased/decreased by various effects. Slash would do 100% of the character's damage stat, Arrows would do 50%, Heavy Slash would do 200%, etc. If the damage stat doubles, all of the spells deal double damage. 
> 
> The benefit is that we actually have a way to give damage bonuses to players. And it wouldn't be a flat increase that ends up OP on Arrow and un-noticeable on Megaslash, it would be inherently balanced / proportional. Things like Empower can apply to any unit, including Spellmasons, without any weird edge cases. We can give damage bonuses via Runes, power-circle auras, spells, support units, boss mechanics (I'm thinking of some cool stuff), meta progression, even items or something if you go crazy with it. Damage could be a stat option when allocating points, which is kind've interesting to think about.
> 
> Not sure if there's a downside to doing it this way. It's a pretty common system so I don't think it'd be unintuitive, plus it would only really apply if the player has run into one of these damage changing effects, such as casting empower on themselves. Even then, the tooltip can use the calculated damage value, and predictions will handle everything else just fine.
> 
> Would probably only take ~3 hours to implement it, or about an hour to push a small example with Slash / Arrow / Empower if you're not sold on it.

**Comment by jdoleary** [comment]
I wonder if this would be OP with empower.  How would we balance this?

**Comment by SoulMuncher** [comment]
It would be pretty strong, but since empower is a modifier that disappears at the end of each level, I don't think it'd be OP or game breaking as-is.

I can't think of any other immediate balance issues, but if we did run into some I'm sure they could be fixed. This is a more of a backend change, something that enables new features and possibilities, and balance always comes after that and is changed to fit into the foundational systems of the game.

**Comment by jdoleary** [comment]
Okay let's plan for that to be in a future feature-focused update.  Since we just did a big content update I want to focus on stability for the next 2

**Comment by SoulMuncher** [comment]
Bumping because people keep reporting the "empower not affecting players" bug:
https://discord.com/channels/1032294536640200766/1242894905941168219

**Comment by jdoleary** [comment]
Okay, I'm adding High Priority per community feedback

**Comment by jdoleary** [comment]
Temporarily archiving.  See comment on #788
