### ISSUE TITLE
HIGH PRIO: After dying and restarting, cannot spawn

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#592]
networkHandler.ts:787 Cannot SPAWN_PLAYER, fromPlayer is undefined.

**Comment by SoulMuncher** [comment]
In singleplayer:
- Create a game
- Save it
- Load the save
- Quit to menu
- Create a new game
- "Cannot SPAWN_PLAYER, fromPlayer is undefined."

**Comment by jdoleary** [comment]
clientId is blank

**Comment by SoulMuncher** [comment]
New Repro:

- Master branch [63a2677](https://github.com/jdoleary/Spellmasons/commit/63a2677e1e25abe8c587b2ca8cd7f14269b95238)
- New game
- Spawn
- Quit to menu
- New game
- Can't spawn

**Comment by SoulMuncher** [comment]
Nvm, fixed after running `npm install` 👍
