### ISSUE TITLE
Last Will 2

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#632]
There's already an icon "spellIconLastWill2.png".
Maybe we just make it an "upgrade" of last will and it causes 2 potions to drop instead of just 1?

Thoughts? @SoulMuncher

**Comment by SoulMuncher** [comment]
It doesn't sound like the most exciting upgrade, but I don't really mind it? I don't have any better ideas off the top of my head.

Going to link related issue here in the meantime ([Stacking Last Will](https://github.com/jdoleary/Spellmasons/issues/90))
