### ISSUE TITLE
Sprite size increases on game reload

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#657]
https://discord.com/channels/1032294536640200766/1032294537235812404/1232568383359287388

maybe related:
https://github.com/jdoleary/Spellmasons/issues/638
https://github.com/jdoleary/Spellmasons/issues/464

**Comment by SoulMuncher** [comment]
> It was just summoned with multiple stacks so it started big
I feel like I've seen similar things happen with bloated stuff though

Helpful info.

Could be that the sprite scale is being saved and then increased again by modifiers and strength-sprite-scaling. The sprite scaling from strength might be fixed with [this commit](https://github.com/jdoleary/Spellmasons/pull/641/commits/0babe67636af4657060f23758cf727bdb4059b3e) in [the Goru PR](https://github.com/jdoleary/Spellmasons/pull/641)

**Comment by jdoleary** [comment]
I'll try to reproduce, thanks
