### ISSUE TITLE
Goru revives players on wrong faction

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#672]
https://discord.com/channels/1032294536640200766/1233805944325148815

Goru shouldn't prime player corpses

**Comment by SoulMuncher** [comment]
@jdoleary 

I'm not sure how this is happening.

- The Goru only resurrects corpses that have the primedCorpse modifier
- The only way to get the primedCorpse modifier is from the Goru directly
- The Goru already filters out player controlled units when applying the primedCorpse modifier

Is the player somehow gaining the modifier through other means? Contaminate wouldn't spread it, is there anything else that transfers modifiers? Soul Shard?
Is the player being resurrected in some other way?

**Comment by jdoleary** [comment]
Hmm, no idea. I'll have to think on how this happened.

**Comment by jdoleary** [comment]
The user responded that it had something to do with Undying modifier instead of primed.
If we still can't reproduce it, let's just add a special check that ensures that player unit faction never gets changed on res
