### ISSUE TITLE
Polymorph sprite offset

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#674]
https://discord.com/channels/1032294536640200766/1032294537235812404/1233830127410872400

**Comment by jdoleary** [comment]
This probably applies to Ancient and Glop.
I verified that ancient is aligned properly on it's own, so yes this is due to polymorph

**Comment by SoulMuncher** [comment]
@jdoleary
The player changes back to their normal sprite while casting, so changing the offset here causes visual issues with that.

I briefly looked at making the player use the polymorphed unit's attack animation, but this was problematic too, since different units play their animations in different ways, and it looks like I'd have to hardcode it for each (playComboAnimation vs playAnimation)

Think we should just leave this one out?

**Comment by jdoleary** [comment]
Okay let's backburner this for now, I want to prioritize the gameplay issues first
