### ISSUE TITLE
Spells won't cast if another player queued spells before them

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#678]
https://discord.com/channels/1032294536640200766/1233957742268514315/1233957742268514315

**Comment by SoulMuncher** [comment]
@jdoleary 
Not much information to work with here, but I did a quick repro attempt and everything worked fine on my end. Could've been a combination of a bunch of things, that made the reporter think their spell didn't go through, maybe the multiplayer channeling delay + a refund, or players had already ended turns or something and it was added to queue after the turn was over, I don't know. Kinda leaning towards closing this one as invalid and coming back to it if it gets reported again
