### ISSUE TITLE
5 stat points in multiplayer? Different from hotseat?

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#682]
https://steamcommunity.com/app/1618380/discussions/0/6352962692743231282/
Caiden: Not sure if it's intentional, but hotseat we only get three points per level. In multiplayer we got five.

**Comment by SoulMuncher** [comment]
I'm so confused by this, not sure how they are getting 5 stat points in multiplayer.
It should always be 3 (or 4 for the spellmason class)

**Comment by jdoleary** [comment]
Yeah I'm not sure either, haven't tried to repro yet
