### ISSUE TITLE
Multiplayer hangs

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#683]
https://steamcommunity.com/app/1618380/discussions/0/6352962692743231282/
> Hello!
Love the new spells, UI changes, and enemy outlines. Very cool.
Sadly, multiplayer is still having issues. We couldn't get far enough to text the desync.
When we press spacebar to end our turn, it just hangs.
Both of us have 'Ready for next turn' in the top left, but nothing moves or happens. Saving the game and restarting seems to fix it for a map or two, but then it happens again.

**Comment by SoulMuncher** [comment]
Keeps getting reported. Some [more info](https://discord.com/channels/1032294536640200766/1032294537235812404/1239969287993692281). Maybe related to freeze

**Comment by jdoleary** [comment]
More context, may help with reproduction:
https://steamcommunity.com/app/1618380/discussions/0/4355621552663491512/

**Comment by jdoleary** [comment]
More context:
NoZ
OP
 — Today at 4:57 PM
I think we might have used a freeze urn, but not the spell. Not 100% sure though
We managed to "save" the run by loading the save at the start of the turn
But we were sent back to just before hopping through a portal

**Comment by jdoleary** [comment]
JordanO — Today at 6:57 PM
I just realized a way we can "force" a reproduction, a custom message that runs only on server that puts it into the bad state
so like it'll set one player as unreaded, while the clients are ready
and then we try ending turn and see if it gets stuck
if that doesn't do it then it's probably the message queue theory

**Comment by SoulMuncher** [comment]
May 15: [Latest discord convo and repro/fix ideas](https://discord.com/channels/@me/1179829034100740136/1240410117912924171)

**Comment by SoulMuncher** [comment]
Okay, I'm kind've aple to reproduce this, but I haven't gotten it 100% "stuck" yet

- Online game with 2 players
- P2 ends turn
- P1 selects P2 and uses admin bar to induce server desync - end turn to false
- P1 ends turn
- Both clients show turn as "Ready for next turn", but the game does not progress
- P1 can end turn as many times as they want and the game won't progress
- Game progresses as soon as P2 ends turn again, since it corrects the server desync

**Comment by SoulMuncher** [comment]
Interestingly, if you freeze P1, their cooldowns and mana cost will decrease, as if the turn phase has changed, but nothing else happens on the server.

**Comment by SoulMuncher** [comment]
If we find someone experiencing the bug and watch their developer console, could we rule in/out the message queue issue?

Is there a reliable way to force a huge message queue?

**Comment by jdoleary** [comment]
You can just make a message that never resolves.  Make it async and await a new promise that never resolves

**Comment by jdoleary** [comment]
logView useful filter
Filter: `setFilter(l => l.v == '1.35.4' && !l.m.includes('Stat Point:') && !l.m.includes('Upgrade card:') && !l.m.includes('Upgrade mageType:'))`

**Comment by jdoleary** [comment]
Possibly related to Arrow says `THE HAM FACE` in discord

**Comment by jdoleary** [comment]
Logs say it might be SET_PHASE on the client.  If so it must be stuck on 
`      await underworld.initializeTurnPhase(phase);`

**Comment by jdoleary** [comment]
All are stuck on phase 3 except one which is stuck on phase 2.  Those are NPC_ENEMY (phase 3) and NPC_ALLY (phase 2). So it's stuck initializing npc phases

**Comment by jdoleary** [comment]
also:
```
onData queue: growing unusually large SET_PLAYER_POSITION {"fromClient":"76c12f77-960e-4c1c-9518-c63087c560a1","time":1715953929011,"type":"Data","payload":{"type":2,"position":{"x":652,"y":548.5298999999883},"stamina":-1.687718201992272}} Payload Types: END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN,END_TURN
```

**Comment by jdoleary** [comment]
I was able to create a state where both players were readied but it didn't progress.  Player one cast a bunch of arrows and ended turn, player two cast Push while arrows were flying and ended turn.
After spells it was in the weird state, but player 2 re-ending turn jogged it and it started working again

**Comment by jdoleary** [comment]
Maybe the answer is that when players are synced and the client keeps their own player information if there is a desync between the end turn state of the current player and the server it resends END_TURN

**Comment by jdoleary** [comment]
I've tried to reproduce by making a spell never resolve, casting it, and joining with another player.  It doesn't exactly jog the game out of the softlock like I witnessed with the existing softlock.  At somepoint casts begin to happen again, but I'm not sure why yet and it's definitely not immediate after the player joins.

**Comment by jdoleary** [comment]
If a spell racetimeouts it still needs to run the end cast logic that sets the player currently casting to not currently casting so that other spells can cast.
This is not handled by racetimingout the message in the messageQueue

**Comment by jdoleary** [comment]
Questions to answer:
- [ ] When a spell times out why do the next spells not trigger?

Experiment:
- Setup
  - There is a (modified) 60 second processNextInQueue timeout
  - There is a 20 second playComboAnimation raceTimeout
- Set slash to never resolve.
- 2 players join local multiplayer game
- Player 1 casts slash
  - Note: Server instantly gets spellcasting set to true even though clients haven't
- Player 2 casts arrow
- Game is stuck because slash hasn't resolved yet
- Now I wait to see how it gets unstuck
- EVENTS:
  - After 10 seconds we get a `reportIfTakingTooLong Slash`
  - After 20 seconds we get a `raceTimeout: playComboAnimation: playerAttackSmall`
    -  And the queue is "Done" processing that message because it timed out
    - The queue now moves onto Player2's arrow spell
    - This invokes progress gamestate because the server has successfully processed the arrow spell
  - After 30 seconds `spellCasting` is set to true and Player 1 animates but nothing happens
  - After 50 seconds, Player 2's arrow finally casts.
- Spells can now be cast freely

**Comment by jdoleary** [comment]
Not sure if #753 actually fixed this or not, so this may need to get reopened

**Comment by jdoleary** [comment]
- [ ] Could `      await this.progressGameState();` in Underworld.ts of endPlayerTurn be the cause?

**Comment by jdoleary** [comment]
![image](https://github.com/jdoleary/Spellmasons/assets/6413317/078981ac-7eba-40c5-96f6-4422d32dd8e4)

Attempting to fix NPC Spellmason timeouts 54edb6fe
NPCs can move or cast but not both, no actions can have two awaits in them, this is a foot gun

**Comment by jdoleary** [comment]
Unable to end turn because caster is undefined
394

**Comment by jdoleary** [comment]
Hasn't been reported in a while.  Closing, assumed fixed
