### ISSUE TITLE
Can't spawn in hotseat

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#687]
https://steamcommunity.com/app/1618380/discussions/0/6352962692743231282/

> Loading a Hotseat game seems to break things. When ending the first person's turn, the second person cannot place their character.
We got to a new level, I placed my character, then saved the game.
On loading, I took my turn, then hit spacebar. It wouldn't let us place the second character.

**Comment by jdoleary** [comment]
I wonder if this is due to my portal refactor

**Comment by SoulMuncher** [comment]
I can repro this on master, but not in #691
