### ISSUE TITLE
Buff Suffocate and Poison

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#69]
Branching this off from #14 so it doesn't get forgotten.

**Comment by jdoleary** [comment]
Also: Stacking Suffocate on glop with 2 turns left doesn't seem to do anything.
Any time Suffocate is applied it should  _at least_ reduce the "turns till death" by 1

**Comment by SoulMuncher** [comment]
I like the idea of suffocate being a sort've "exponential" poison, only dealing damage when it becomes lethal.

Also:
Found some potential bugs with suffocate that may significantly affect it's "damage output" under certain conditions. Will investigate and add more info tomorrow.

**Comment by jdoleary** [comment]
A way to show it would definitely be useful.  I like the idea of a purple bar (like a countdown timer that fills up).  Maybe it's just 1px that goes over the health bar.
