### ISSUE TITLE
Color Replace Filter broken again

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#695]
https://steamcommunity.com/app/1618380/discussions/0/4356746316586076704/

**Comment by SoulMuncher** [comment]
Discussion: https://discord.com/channels/@me/1179829034100740136/1233540269505511445
> S: Color replace filter is broken on pretty much all units
> J: I'll re-export in PNG-32 and see if that affects it
> S: I just retested WITHOUT pulling and it's gone
> (a few hours pass)
> S: Color filter is broken in steam build

Related: https://github.com/jdoleary/Spellmasons/issues/33

**Comment by jdoleary** [comment]
I'm not entirely sure how this came back or how to fix it since I've never been able to reproduce it on my end but I'd consider this important.  @SoulMuncher, if you are able to reproduce it, maybe I set you up with Texture packer so you can modify the settings and see if you can get it to go away.

**Comment by jdoleary** [comment]
Baalstrum
OP
 — Today at 6:47 PM
For some reason all Blood archers/golems look like the normal versions of themselves all of a sudden. Noticed in my past two runs.
Jordan - Spellmasons Creator — Today at 6:53 PM
Hi Baalstrum, this is something I'm aware of and trying to find a solution too.  Hopefully I'll have it reseolved soon! Thanks for reporting 🙂
oh, extra information, was it not always like this for you?
Have past runs been normal?
Baalstrum
OP
 — Today at 6:54 PM
I feel like I only started noticing after playing multiplayer
Jordan - Spellmasons Creator — Today at 6:54 PM
hmm interesting
Okay thanks for the extra info
Jordan - Spellmasons Creator — Today at 6:55 PM
when was the last time you saw it normal?
within a week?
Baalstrum
OP
 — Today at 6:55 PM
Yes

---
@SoulMuncher it looks like the color filter can break without any update!

**Comment by jdoleary** [comment]
New idea: Since the broken blood golem still has the top of the head colored maybe I should switch up the order in the multi color replace filter

**Comment by jdoleary** [comment]
Reproduced in later levels: https://discord.com/channels/1032294536640200766/1240435453413298246/1253816258647031949

**Comment by jdoleary** [comment]
Can you run a filter in a texture instead of sprite
Could it be that another filter is changing the pixels which explains why the colors aren’t changing correctly
