### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#707]
Reported 3 messages down:
https://steamcommunity.com/app/1618380/discussions/0/4356746484461903820/

**Comment by jdoleary** [comment]
@SoulMuncher This is an important one, I've noticed this on servers and haven't figured out what's causing it yet.  Let's leave this one open

**Comment by DeathmonkeyJ** [comment]
Not sure if it helps, but I've noticed ram usage increasing A LOT while moving the camera using middle mouse dragging.

**Comment by jdoleary** [comment]
2nd report of ram increasing while moving the camera: https://discord.com/channels/1032294536640200766/1241088440234279032/1241154193469997151

**Comment by jdoleary** [comment]
The culprit is `underworld.syncPredictionEntities()`, the prediction entities are not getting cleaned up.

**Comment by jdoleary** [comment]
Solution is probably to have a persistent prediction copy that is ON the unit object only  (instead of in a unitsPrediction array that is separate) and update it rather than creating a new one with this.units.map and this.pickups.map

**Comment by jdoleary** [comment]
Fixed by 3d87415
