### ISSUE TITLE
Player size is too big when merging

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#711]
https://discord.com/channels/1032294536640200766/1238083497671921727/1238083497671921727

Maybe it should reset between levels or we should have a more aggressive scale falloff algorithm

**Comment by jdoleary** [comment]
Solutions:
- [ ] Reset scale between levels
- [ ] Harder falloff limit on merge scaling?

**Comment by SoulMuncher** [comment]
Player size probably shouldn't increase with merge anyway, since they are only gaining temporary stats? @jdoleary
