### ISSUE TITLE
runPrediction() on MouseMove is different from realtime result

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#721]
Hard to explain, but I'll get a video.

If a unit is on the edge of a targeting radius, such as target cone, and you move the mouse one pixel away so that the unit is no longer in the radius, it will still PREDICT targeting the enemy, but the actual spell will not.

This is problematic because it's common to try and "perfectly line up" a targeting spell to hit a certain number of enemies, and all that effort will be wasted on a spell not doing what it says it will.

**Comment by SoulMuncher** [comment]
https://github.com/jdoleary/Spellmasons/assets/68413161/cbfbc648-7db2-4ab3-af60-6aa7a1bb3c5c

**Comment by jdoleary** [comment]
Very helpful video context, do you know what's causing this?

**Comment by SoulMuncher** [comment]
Not exactly, it just seems like the predictions are updating to the 2nd to last cursor position, but then the spell casts at the current cursor position, so there's a discrepancy there.
It could be do to lower level gameloop timing stuff, maybe the cursor position is changing after runPredictions is called

**Comment by SoulMuncher** [comment]
Bumping because this is became more prevalent after the introduction bouncing arrows: #879
