### ISSUE TITLE
health desync

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#722]
Expresso Depresso
OP
 — Yesterday at 8:16 PM
Me and a friend spawned. I was an archer. I shot a slime to drop him to 40 health. I saw 40 health, my friend saw 50. I leveled up when he hit it with two slashes. He had to use one more slash to kill it, then he did not level up. We were playing on Shark server at the time

https://discord.com/channels/1032294536640200766/1239370682610094231/1239370682610094231

**Comment by jdoleary** [comment]
Expresso Depresso
OP
 — Yesterday at 8:25 PM
There was another instance of it happening next stage
Jordan - Spellmasons Creator — Today at 6:22 AM
Thanks for the report.  Did it happen in exactly the same way in the next stage or were different spells cast?
Expresso Depresso
OP
 — Today at 10:51 AM
Nope it happened in the exact same way I cast like 7 arrows and one just didn't seem to be casted on his end for some reason

**Comment by SoulMuncher** [comment]
this is likely an effect of #628 
which is likely an effect of #381
