### ISSUE TITLE
Allow Contaminate to increase stacks of already-held curses

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#74]

**Comment by SoulMuncher** [comment]
If it simply adds the curse amounts together, every contaminate could double the number of curses on each nearby target. Combine that with targeting spells and could easily chain freezes forever or get 1000 stacks of poison/suffocate on the first deathmason. This would be incredibly broken. Damage curses are also being buffed, and have a class dedicated to casting them efficiently.

I'm going to take a small step towards this change by just having contaminate overwrite lower curse values at first. If I cast contaminate on a poison 10 unit, all units in range with a lower level of poison or no poison at all will go up to poison 10. If you still want to change it after trying it out, it should be pretty easy.

**Comment by jdoleary** [comment]
That's a good call.  I agree with your judgement here
