### ISSUE TITLE
Mechanic Idea: Souls as resource

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#749]
What if soul magic cost "Soul units" instead of mana.  
Characteristics:
- Soul units would persist across levels
- Soul units can't be recouped once spent
- You earn them from killing enemies?

This idea maybe needs some work but could be cool
It could bring in more spells like a damage spell that consumes souls to deal damage.  Lot's that could be done here.

**Comment by SoulMuncher** [comment]
Duplicate: #759
