### ISSUE TITLE
Beam spells or spells that reflect off of walls

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#765]
https://discord.com/channels/1032294536640200766/1032294537235812404/1242903165129724007

@Sana

**Comment by SoulMuncher** [comment]
Would love an upgrade of target arrow that is essentially a projectile "disc" that bounces off walls/units and each stack adds a another bounce / targeting location.

**Comment by SoulMuncher** [comment]
I already added logic for wall-reflection somewhere in force moves logic. ReflectVelocityOnWall() in moveWithCollision.ts
