### ISSUE TITLE
Host can force end turn?

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#769]
https://discord.com/channels/1032294536640200766/1070397640765874327/1242986860851101788

> Side note : When playing multiplayer, when the host presses space (or ready) sometimes the turn plays out even when the other player didn't press it. Idk if it was happening to just me or is it on purpose but yeah, saw that

curious if this has anything to do with:
#683
#677

**Comment by jdoleary** [comment]
This is a recent fix, any player sends all the other player ready states with their END_TURN message now.
The fact that it's unexpectedly ending turns might point to a deeper problem with how player end turn states are synced across clients

**Comment by jdoleary** [comment]
Fixed in c14cfab988cd37277a66a42e262073b122082b0a
