### ISSUE TITLE
Calamity disables weaker spells

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#78]
Teamate took a calamity to disable mega slash, and it disabled giant slash as well.
In addition, I don't think they had mega slash unlocked at this time, so the calamity probably shouldn't have appeared.

May be specific to giant slash or a global calamity issue.

**Comment by jdoleary** [comment]
I think I want to eventually remove calamities for other ways of better end game challenge.  So I'm going to mark this as low prio for now.

**Comment by SoulMuncher** [comment]
Closing since calamities have been replaced with Waves
