### ISSUE TITLE
Fix Idea: Can't cast one spell while another is in progress

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#784]
Might fix
#401 
#729 
#783 

(potentially others)

We could just return the click handler if a spell is currently animating, the same way we do if you're dead or don't have enough mana

**Comment by jdoleary** [comment]
What's weird is this is already supposed to be in effect.  If you click to cast a spell while another is in progress it is supposed to queue it up and then trigger it once the previous spell has finished.  This is where the "spellmason looking at the book" channeling animation comes in.  
That's the behavior I want.  Just returning the click handler, i think, would be frustrating.  Players are used to queueing their spell up.
So I'd say the answer is whatever prevents the aforementioned bugs while still allowing players to queue up their spell.
