### ISSUE TITLE
Blood Curse gives a copy of the spell

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#80]
I gave a teamate blood curse, and they weren't able to pick a spell on their next spell unlock.
I have a suspicion that getting a new spell from any source (such as picking a mage type) may cause this issue.

**Comment by jdoleary** [comment]
Yes, this is a bug, I forgot that giving blood curse also gives the spell to the player. (This was back when vampires could give it to you by biting you - a very very old idea where you could become a vampire and I guess the "giving" of blood curse just stuck around). Any spell that is given (not via an upgrade) needs to be added to the globalThis.freeSpells array.

OMG now that I'm thinking about it, this is probably what's causing one player to report losing summon spells.  freeSpells shouldn't be on the global, it should be on the IPlayer object or else it wont be persisted.  I'm going to create a new event for this in particular.  For this issue, the "giving" of blood curse spell should just be removed.
