### ISSUE TITLE
Summon Targeting Overlap

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#800]
[Summon Decoy + Bloat] should always target the ground, summon a decoy, and then add bloat to it.

If you cast this spell while your cursor is over a golem, that golem will be added to the initial targets list and will also recieve bloat. Expected: It shouldn't target the golem because you're starting the spell with a summon

**Comment by jdoleary** [comment]
I'm okay with this side effect.  Any unit under the cursor gets targeted by design
