### ISSUE TITLE
Decoy lost Blood Curse

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#81]
Noticed a decoy lose the health multiplier from blood curse after being repeatedly attacked by a vampire.
Note: The decoy still showed it had blood curse, but its max health had gone back to the pre-curse amount.

If no source is found in the code, it could also be a multiplayer sync issue?

**Comment by jdoleary** [comment]
Hmm, vampires are supposed to _apply_ blood curse when they attack.  Maybe it's somehow toggling it on and off?

**Comment by SoulMuncher** [comment]
Haven't been able to repro this. I think it was a multiplayer sync issue.

**Comment by jdoleary** [comment]
Reopening since #110 didn't resolve it but labeling it as needs repro and low priority since it is uncertain

**Comment by SoulMuncher** [comment]
Been two months since #110 and I haven't seen this again, closing this since it was probably resolved. Will reopen if neccesary 👍
