### ISSUE TITLE
Ideas to balance "Target Everything Builds"

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#812]
> NoZ
 — 06/02/2024 8:06 AM
After a certain number of levels, many strategies just involve a series of target similar/connect/etc. and then damage.

To add more nuance, new types of enemies could be added, some examples below:
A type of enemy that when target at the same time as a target of another type, will simply split/buff enemies/damage user/remove user mana/other penalty. This makes the user have to more carefully target enemies in a specific order.
A type of enemy that has to be targeted individually, eg. multiple of that specific enemy either can't be targeted at the same time or other penalty.
A type of enemy that halves damage taken per targeted enemy after 1, so 1 enemy targeted takes full damage, 2 takes 0.5.
A type of enemy with reversed heal/damage meaning if you target it at the same time as other units to kill them, you will heal that unit past its max health.
A type of enemy that blocks attacks to other units (near or globally) until killed + 1 turn.
A type of enemy that absorbs all damage of other enemies chained in that spell, except for that type to prevent loops.
Hydra? A type of enemy split into two types of enemies head and body. While the body is alive, killing a head will spawn 2 new heads.

This type of mechanic seems better than simply making targeting more expensive etc. since that just delays the problem.

**Comment by jdoleary** [comment]
"Can't be moved with spells"

These could be modifications that happen to existing enemies

**Comment by SoulMuncher** [comment]
Protection aura idea in #814

**Comment by jdoleary** [comment]
New modifiers waiting to be used:
- [ ] slime
- [ ] Target Immune

**Comment by jdoleary** [comment]
These should increase in frequency as you get into plus levels so that the difficulty sincerely ramps without being tedius

**Comment by jdoleary** [comment]
Maybe events that can hurt you that aren't enemies, such as a meteor and it warns you one turn ahead
