### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#835]

**Comment by jdoleary** [comment]
https://www.reddit.com/r/gamedev/comments/1dm3gxh/comment/l9t7kyw/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

"UI matters so much"

**Comment by SoulMuncher** [comment]
Sent first batch in [discord](https://discord.com/channels/@me/1179829034100740136/1259332392565608489)

**Comment by jdoleary** [comment]
Updated! Thank you!
