### ISSUE TITLE
Target arrow refunds cost of the arrow if it hits a wall, but still executes the connected spells

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#854]
https://discord.com/channels/1032294536640200766/1259602595245326387/1259602595245326387

Apotheosis
OP
 — Yesterday at 4:11 PM
For instance, using a summoning and target arrow, when the arrow hits a wall it refunds the cost of the arrow saying no target found, but still summons the mob where the arrow hits (at the normal cost of the summoning spell)

**Comment by SoulMuncher** [comment]
@jdoleary 
Grabbing this one since I'm working on arrow stuff
