### ISSUE TITLE
Repel Balance

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#87]
Repel can easily substitute for most other movement spells with no additional cost.

Does it need a nerf?

While repel *is* very powerful and outshines the other movement spells, I think it's also very fun to use, so we should be careful in adjusting it.

**Comment by jdoleary** [comment]
Agreed, I think it should just be more expensive to account for it being more flexible than the others.  Maybe 20 mana instead of 10?

**Comment by SoulMuncher** [comment]
Making it require push (and vortex require pull) could also make the player invest more to be able to use it.

Note: There hasn't been a single time where I was happy to have vortex, lol. I need to tinker with it more, but it feels sooo weak compared to repel, which should be its equal and opposite counterpart. Maybe this is an issue with circle being expensive / cast range being a bit limited.

**Comment by jdoleary** [comment]
> Making it require push (and vortex require pull) could also make the player invest more into movement spells to be able to use it.
> 
> Note: There hasn't been a single time where I was happy to have vortex, lol. I need to tinker with it more, but it feels sooo weak compared to repel, which should be its equal and opposite counterpart. Maybe this is an issue with circle being expensive / cast range being a bit limited. Maybe it needs a slight mechanical rework/enhancement, or improved interaction with targeting spells. I'll do some testing

I think vortex is secretly very powerful.  it's terrible on it's own, but if you pair it with target similar, you can pull someone from across the entire map.  It pairs very very well with lots of targeting spells.  I've seen players use it extensively for map-wipes
