### ISSUE TITLE
Ricochet Arrow

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#876]
MΣMΣ_MΛП
OP
 — Today at 2:52 AM
Its the same as the normal target arrow except it can bounce off a wall once. Stacking the ricochet target arrow would increase the bounces. This could be a nice addition to the game and would provide strategic use

**Comment by SoulMuncher** [comment]
related

https://github.com/jdoleary/Spellmasons/issues/18

https://github.com/jdoleary/Spellmasons/issues/765
