### ISSUE TITLE
Spell prediction damage + mana barrier = can't cast

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#947]
Any time you would take damage from a spell while you have mana barrier, that spell cannot be cast. This prevents dashes/pushes through liquid, meteor/bloat/shatter/etc. aoe's, some soulbind combos

Repro:
- Have 20 mana and mana barrier
- Want to dash through liquid to get to a health potion/get away from enemies
- Dash prediction states player takes damage, damage causes mana to = 0 due to mana barrier
- Damage brings mana down to 0 due to mana barrier
- Spell cost occurs AFTER spell effect
- 0 remaining mana is not enough to pay dash cost
- Spell cannot be cast

Expected: Mana cost should happen up front, allowing me to dash
Related: #182

**Comment by jdoleary** [comment]
We may want to omit mana barrier until this gets fixed

**Comment by jdoleary** [comment]
Fixed in #182
