### ISSUE TITLE
Bloat radius on select

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#98]
You should be able to see the explosion radius of a unit affected by bloat when you select (not target) them.

Edit: Meaning a circle around them in the game world, not the numerical radius stat.

**Comment by jdoleary** [comment]
What about other curses?  If a player has all the curses, which should show on select and which shouldn't?  This could be useful, but might not be necessary until they're predicted to die as it does now.  I'm on the fence on this one.

**Comment by SoulMuncher** [comment]
@jdoleary 
> What about other curses? ... I'm on the fence on this one.

Updated original post for clarity. Most curses and status effects don't have anything to show outside of the stat panel: Slow, Freeze, Suffocate, Poison, Blood Curse, Shield, Conserve, and Last Will. They don't and still wouldn't do anything on screen because they have no reason to. Bloat does, and I think that it's explosion radius should be visible to the player as most other ones are. (Exploding arrow, Urns, etc.)

In the current version of the game, I don't there's a way to see how big the explosion radius of bloat is. It feels pretty bad, especially when you add multiplayer desync and somewhat broken predictions. There isn't a reliable way to know if you're going to damage the things you're trying to damage, and not damage the things you don't want to.

**Comment by jdoleary** [comment]
Okay I'm open to this. 
It _should_ always show the bloat circle when a unit is predicted to take fatal damage by a spell... now that I think about it, it _doesn't_ show the circle if it will take fatal damage indirectly (via poison for example).  So yes, let's try showing the radius on select 👍
