### ISSUE TITLE
Balance bolt

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#981]
Xulqelyat — Yesterday at 10:43 PM
@SoulMuncher I think making bolt stack with targeting spells might go against what the spell is and make it too powerful
SoulMuncher — Yesterday at 10:43 PM
agreed
Xulqelyat — Yesterday at 10:43 PM
the point is that it already is a aoe that goes between everything around the target
electricity shouldnt ark between 2 tings that can be on opposite sides of the map
SoulMuncher — Yesterday at 10:44 PM
yeah there was another discussion about that somewhere on the discord, I think we're going to update it again
Liese — Today at 2:26 AM
yeah this is crazy bolt is too good now
i wish there were some middle ground, bolt sucks in its previous state
i guess of note, plus radius was used twice, which is why bolt cascaded across all the different monsters so easy

**Comment by jdoleary** [comment]
Or maybe we decrease the damage a lot?  It feels like it's either way too powerful with lots of enemies or way not powerful enough
SPGALTRM — Today at 5:45 AM
maybe set a chain limit and let it chain multiple time throught 2 enemys?
like back and forth
Jordan - Spellmasons Creator — Today at 5:46 AM
ah so chaining would be limited by bolt stack but it still scales with targeting? Maybe that would do it
SPGALTRM — Today at 5:46 AM
like 8 damage 3 chains max and it goes to one asrcher back and forth 3 times for 28 damage
SPGALTRM — Today at 5:50 AM
going more into this it would stack with target circle or something like that by adding another 3 chains between targets but it capps the damage at 48  so like 1 archer takes 24 and anohter takes 24 not mkaing it bad but viable and if u do add a damage cap maybe like tweak the damage and decide how much u damage u want it to
Jordan - Spellmasons Creator — Today at 5:51 AM
ooh what if the damage was relative to the number of units connected?
Like + 1 damage per connected unit or something.  Starts at 0 damage.  Stacks increase number it can chain to but don't increase damage
It would need fine tuning but that might fix the issue
Xulqelyat — Today at 9:44 AM
I like the idea of bolt doing maybe less dmg but what if we split it up
like one version  that only links to everything in the circle stacking based on how many links there are to do inane small area dmg
then another spell thats more a flat higher dmg that arcs further for less dmg but more targets

**Comment by SoulMuncher** [comment]
related
- #793 
- specific comment on bolt: https://github.com/jdoleary/Spellmasons/issues/344#issuecomment-2184114718 
- discussion after bolt-targeting-buff: https://discord.com/channels/1032294536640200766/1271864511048974347/1271871024421539953

**Comment by SoulMuncher** [comment]
I'm not 100% how it'd feel without testing it, but I really want to try something like this:
- X damage and 1 chain
- Quantity adds +1 chain
- Bolt deals more damage/has more chaining radius per chain remaining
