### ISSUE TITLE
Test Bounty Hunter in multiplayer

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#995]
how does it work if one player kills another's bounty

**Comment by SoulMuncher** [comment]
Bounties don't necessarily belong to anyone (I thought that would be too confusing in multiplayer) so it just spawns one bounty on the opposing faction per bounty hunter

**Comment by jdoleary** [comment]
Fixed: 00540942dbdf54065d53760894b73cb572de564d
